name: edge
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=24
  - ffmpeg
  - libsndfile
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0
      - torchvision==0.23.0
      - torchaudio==2.8.0
      - -r requirements-edge.txt
      - pytorch3d @ git+https://github.com/facebookresearch/pytorch3d.git@b6a77ad7aaf41ed90fca80ce6a2bac3c462a7881
