#!/usr/bin/env bash
set -euo pipefail

# V34 inference/training launcher for the semantic-router version of Event-RAG.
# This keeps the previous graceful boundary repair, but moves the main
# prevention mechanism upstream into semantic, contact and constrained-warp
# retrieval gates.

ROOT="${EDGE_ROOT:-/home/disk/lsm/storage/EDGE}"
cd "$ROOT"

export V34_BOUNDARY_COMPAT=1
export V34_COMPAT_HARD_PRUNE="${V34_COMPAT_HARD_PRUNE:-1}"
export V34_BOUNDARY_COMPAT_WEIGHT="${V34_BOUNDARY_COMPAT_WEIGHT:-1.80}"
export V34_COMPAT_SEMANTIC_HARD_PRUNE="${V34_COMPAT_SEMANTIC_HARD_PRUNE:-1}"
export V34_COMPAT_MAX_POSE_JUMP="${V34_COMPAT_MAX_POSE_JUMP:-0.35}"
export V34_COMPAT_MAX_CONTACT_JUMP="${V34_COMPAT_MAX_CONTACT_JUMP:-0.45}"
export V34_COMPAT_MAX_CONTACT_BINARY_JUMP="${V34_COMPAT_MAX_CONTACT_BINARY_JUMP:-0.50}"
export V34_COMPAT_MAX_SUPPORT_COUNT_JUMP="${V34_COMPAT_MAX_SUPPORT_COUNT_JUMP:-0.50}"
export V34_COMPAT_MAX_TRANSITION_COST="${V34_COMPAT_MAX_TRANSITION_COST:-0.72}"
export V34_COMPAT_FORBID_AERIAL_PLANTED_SWITCH="${V34_COMPAT_FORBID_AERIAL_PLANTED_SWITCH:-1}"

export V34_SEMANTIC_EDGE="${V34_SEMANTIC_EDGE:-1}"
export V34_SEMANTIC_EDGE_HARD_PRUNE="${V34_SEMANTIC_EDGE_HARD_PRUNE:-1}"
export V34_SEMANTIC_EDGE_WEIGHT="${V34_SEMANTIC_EDGE_WEIGHT:-1.25}"
export V34_MOTIF_MEMORY_WEIGHT="${V34_MOTIF_MEMORY_WEIGHT:-0.75}"

export V34_RELAX_CONSTRAINTS_ON_EMPTY="${V34_RELAX_CONSTRAINTS_ON_EMPTY:-1}"
export V34_RELAX_COMPAT_ON_EMPTY="${V34_RELAX_COMPAT_ON_EMPTY:-1}"
export V34_RELAX_SEMANTIC_ON_EMPTY="${V34_RELAX_SEMANTIC_ON_EMPTY:-1}"
export V34_RELAX_COMPAT_PENALTY_WEIGHT="${V34_RELAX_COMPAT_PENALTY_WEIGHT:-5.00}"
export V34_RELAX_SEMANTIC_PENALTY_WEIGHT="${V34_RELAX_SEMANTIC_PENALTY_WEIGHT:-4.50}"
export V34_RELAX_CONTACT_PENALTY_WEIGHT="${V34_RELAX_CONTACT_PENALTY_WEIGHT:-2.00}"

export V34_WARP_HARD_PRUNE=1
export V34_WARP_MIN="${V34_WARP_MIN:-0.92}"
export V34_WARP_MAX="${V34_WARP_MAX:-1.12}"
export V34_WARP_RELAX_ON_EMPTY="${V34_WARP_RELAX_ON_EMPTY:-1}"
export V34_WARP_RELAX_MIN="${V34_WARP_RELAX_MIN:-0.82}"
export V34_WARP_RELAX_MAX="${V34_WARP_RELAX_MAX:-1.30}"

export V34_BOUNDARY_INPAINT="${V34_BOUNDARY_INPAINT:-1}"
export V34_INPAINT_ON_RELAXED_CONSTRAINT="${V34_INPAINT_ON_RELAXED_CONSTRAINT:-1}"
export V34_LATENT_SNIPPET_BLEND="${V34_LATENT_SNIPPET_BLEND:-1}"
export V34_USE_GPU_RETRIEVAL="${V34_USE_GPU_RETRIEVAL:-1}"
export V34_FAIL_ON_UNSAFE_BOUNDARY="${V34_FAIL_ON_UNSAFE_BOUNDARY:-0}"
export V34_DEFER_UNSAFE_BOUNDARY="${V34_DEFER_UNSAFE_BOUNDARY:-1}"
export V34_HANDSHAKE_FALLBACK_ON_UNSAFE="${V34_HANDSHAKE_FALLBACK_ON_UNSAFE:-1}"

export RUN_ID="${RUN_ID:-v34_semantic_router_$(date +%Y%m%d_%H%M%S)}"
bash scripts/launch_v34_graceful_pipeline.sh "$@"
