#!/usr/bin/env bash
set -euo pipefail

cd /home/disk/lsm/storage/EDGE

# Stable V3H code guards.
# Robust base denoising/reconstruction losses.
export EDGE_V3_BASE_LOSS_STABILITY="${EDGE_V3_BASE_LOSS_STABILITY:-1}"
export EDGE_V3_RECON_SAMPLE_CAP="${EDGE_V3_RECON_SAMPLE_CAP:-200}"
export EDGE_V3_VEL_SAMPLE_CAP="${EDGE_V3_VEL_SAMPLE_CAP:-100}"
export EDGE_V3_BASE_INPUT_CLIP="${EDGE_V3_BASE_INPUT_CLIP:-8.0}"
export EDGE_V3_BASE_DIFF_CLIP="${EDGE_V3_BASE_DIFF_CLIP:-8.0}"
export EDGE_V3_RECON_SCALE_FLOOR="${EDGE_V3_RECON_SCALE_FLOOR:-0.05}"
export EDGE_V3_VEL_SCALE_FLOOR="${EDGE_V3_VEL_SCALE_FLOOR:-0.02}"

# Disable extra raw x0 MSE because predict_epsilon=False already trains x0 directly.
export EDGE_X0_RECON_LOSS="${EDGE_X0_RECON_LOSS:-0}"

export EDGE_V3_LOSS_STABILITY="${EDGE_V3_LOSS_STABILITY:-1}"
export EDGE_V3_CAP_TOTAL_LOSS="${EDGE_V3_CAP_TOTAL_LOSS:-0}"
export EDGE_V3_TOTAL_LOSS_CAP="${EDGE_V3_TOTAL_LOSS_CAP:-50000}"
export EDGE_V3_COMPONENT_LOSS_CAP="${EDGE_V3_COMPONENT_LOSS_CAP:-5000}"
export EDGE_V3_MOTION_ENERGY_LOSS_CAP="${EDGE_V3_MOTION_ENERGY_LOSS_CAP:-2000}"

# Prevent rare pred_x0/FK spikes from exploding support-chain loss.
export EDGE_V3H_CLAMP_PHYS="${EDGE_V3H_CLAMP_PHYS:-1}"
export EDGE_V3H_PHYS_CLIP="${EDGE_V3H_PHYS_CLIP:-6.0}"
export EDGE_V3H_FK_POS_CLIP="${EDGE_V3H_FK_POS_CLIP:-8.0}"
export EDGE_V3H_DIFF_CLAMP="${EDGE_V3H_DIFF_CLAMP:-8.0}"
export EDGE_V3H_TERM_CAP="${EDGE_V3H_TERM_CAP:-25.0}"
export EDGE_V3H_SAMPLE_LOSS_CAP="${EDGE_V3H_SAMPLE_LOSS_CAP:-25.0}"

# Conservative effective support-chain scale.
export EDGE_V3H_SUPPORT_CHAIN_WEIGHT="${EDGE_V3H_SUPPORT_CHAIN_WEIGHT:-0.35}"

# Keep V3 temporal prior active, but not too strong.
export EDGE_X0_RECON_LOSS_WEIGHT="${EDGE_X0_RECON_LOSS_WEIGHT:-0.04}"
export EDGE_V3_TEMPORAL_WEIGHT="${EDGE_V3_TEMPORAL_WEIGHT:-0.025}"
export EDGE_V3_DCT_KEEP="${EDGE_V3_DCT_KEEP:-8}"
export EDGE_V3_TEMPORAL_FEATURES="${EDGE_V3_TEMPORAL_FEATURES:-no_contact}"

# Stable support-chain component weights.
export EDGE_V3H_ROOT_Y_VEL_WEIGHT="${EDGE_V3H_ROOT_Y_VEL_WEIGHT:-0.25}"
export EDGE_V3H_ROOT_XZ_VEL_WEIGHT="${EDGE_V3H_ROOT_XZ_VEL_WEIGHT:-0.04}"
export EDGE_V3H_ROOT_Y_ABS_WEIGHT="${EDGE_V3H_ROOT_Y_ABS_WEIGHT:-0.01}"

export EDGE_V3H_PELVIS_ABS_WEIGHT="${EDGE_V3H_PELVIS_ABS_WEIGHT:-0.01}"
export EDGE_V3H_HIPS_ABS_WEIGHT="${EDGE_V3H_HIPS_ABS_WEIGHT:-0.01}"

export EDGE_V3H_PELVIS_ROT_VEL_WEIGHT="${EDGE_V3H_PELVIS_ROT_VEL_WEIGHT:-0.08}"
export EDGE_V3H_HIPS_ROT_VEL_WEIGHT="${EDGE_V3H_HIPS_ROT_VEL_WEIGHT:-0.07}"
export EDGE_V3H_KNEES_ROT_VEL_WEIGHT="${EDGE_V3H_KNEES_ROT_VEL_WEIGHT:-0.05}"
export EDGE_V3H_ANKLES_FEET_ROT_VEL_WEIGHT="${EDGE_V3H_ANKLES_FEET_ROT_VEL_WEIGHT:-0.04}"

export EDGE_V3H_LOWER_FK_SPEED_WEIGHT="${EDGE_V3H_LOWER_FK_SPEED_WEIGHT:-0.35}"
export EDGE_V3H_LOWER_FK_ACTIVITY_WEIGHT="${EDGE_V3H_LOWER_FK_ACTIVITY_WEIGHT:-0.35}"
export EDGE_V3H_LOWER_FK_RANGE_WEIGHT="${EDGE_V3H_LOWER_FK_RANGE_WEIGHT:-0.25}"
export EDGE_V3H_FOOT_FK_SPEED_WEIGHT="${EDGE_V3H_FOOT_FK_SPEED_WEIGHT:-0.15}"
export EDGE_V3H_FOOT_HEIGHT_WEIGHT="${EDGE_V3H_FOOT_HEIGHT_WEIGHT:-0.08}"
export EDGE_V3H_FOOT_RANGE_WEIGHT="${EDGE_V3H_FOOT_RANGE_WEIGHT:-0.15}"
export EDGE_V3H_LOWER_FK_DCT_WEIGHT="${EDGE_V3H_LOWER_FK_DCT_WEIGHT:-0.005}"

export EDGE_V3H_CONTACT_RECON_WEIGHT="${EDGE_V3H_CONTACT_RECON_WEIGHT:-0.005}"
export EDGE_V3H_CONTACT_SWITCH_WEIGHT="${EDGE_V3H_CONTACT_SWITCH_WEIGHT:-0.01}"
export EDGE_V3H_CONTACT_FOOT_VEL_WEIGHT="${EDGE_V3H_CONTACT_FOOT_VEL_WEIGHT:-0.005}"
export EDGE_V3H_CONTACT_FOOT_HEIGHT_WEIGHT="${EDGE_V3H_CONTACT_FOOT_HEIGHT_WEIGHT:-0.005}"

# Normal run defaults.
export RUN_ID="${RUN_ID:-v3h_footwork_stable_day}"
export EPOCHS="${EPOCHS:-500}"
export PER_BUCKET="${PER_BUCKET:-120}"
export MAX_TOTAL="${MAX_TOTAL:-500}"
export BATCH_SIZE="${BATCH_SIZE:-12}"
export BATCH_SIZE_SMOKE="${BATCH_SIZE_SMOKE:-6}"
export LR="${LR:-1e-5}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

bash scripts/run_v3h_footwork_day.sh
