#!/usr/bin/env bash
set -euo pipefail
MOTION="${1:?motion npy required}"
OUT="${2:-${MOTION%.npy}_v38_contact_filtered.npy}"
SUMMARY="${OUT%.npy}.motion_quality_postprocess.json"
cd "${EDGE_ROOT:-/home/disk/lsm/storage/EDGE}"
export PYTHONPATH="$PWD${PYTHONPATH:+:$PYTHONPATH}"
export V38_CONTACT_DENOISE="${V38_CONTACT_DENOISE:-1}"
export V38_CONTACT_MEDIAN_SIZE="${V38_CONTACT_MEDIAN_SIZE:-5}"
export V38_CONTACT_CLOSE_HOLES="${V38_CONTACT_CLOSE_HOLES:-5}"
export V38_CONTACT_OPEN_SPIKES="${V38_CONTACT_OPEN_SPIKES:-3}"
export V38_CONTACT_LOCK_BLEND_FRAMES="${V38_CONTACT_LOCK_BLEND_FRAMES:-5}"
export V38_BUTTERWORTH_FILTER="${V38_BUTTERWORTH_FILTER:-1}"
export V38_BUTTERWORTH_CUTOFF_HZ="${V38_BUTTERWORTH_CUTOFF_HZ:-4.0}"
export V38_BUTTERWORTH_ORDER="${V38_BUTTERWORTH_ORDER:-2}"
export V38_BUTTERWORTH_STRENGTH="${V38_BUTTERWORTH_STRENGTH:-0.85}"
export V38_BUTTERWORTH_JOINTS="${V38_BUTTERWORTH_JOINTS:-lelbow,relbow,lwrist,rwrist,lhand,rhand,lshoulder,rshoulder}"
python tools/v34_motion_quality_postprocess.py   --motion "$MOTION"   --out "$OUT"   --summary_json "$SUMMARY"   --contact_lock "${V34_CONTACT_LOCK_POSTPROCESS:-1}"   --contact_threshold "${V34_CONTACT_LOCK_THRESHOLD:-0.65}"   --root_y_physics "${V34_ROOT_Y_PHYSICS:-1}"   --collision_ik "${V34_COLLISION_IK:-1}"   --contact_lock_strength "${V34_CONTACT_LOCK_STRENGTH:-0.85}"   --contact_smooth_window "${V34_CONTACT_LOCK_SMOOTH_WINDOW:-7}"   --max_root_correction "${V34_CONTACT_LOCK_MAX_ROOT_CORRECTION:-0.18}"   --floor_clearance "${V34_FLOOR_CLEARANCE_POSTPROCESS:-1}"   --floor_support_damping "${V34_FLOOR_SUPPORT_DAMPING:-0.25}"   --smooth "${V34_OUTPUT_SMOOTH:-0}"
python tools/v38_contact_jitter_delta.py --summary "$SUMMARY" --out "${SUMMARY%.json}.delta.json"
echo "[V38 DONE]"
echo "motion=$OUT"
echo "summary=$SUMMARY"
echo "delta=${SUMMARY%.json}.delta.json"
