#!/usr/bin/env bash
set -euo pipefail
cd /home/disk/lsm/storage/EDGE
mkdir -p logs output/v10_eval
: "${CHECKPOINT:=/home/disk/lsm/storage/EDGE/runs/train_stage45/v9_rag_summary_token_e4/weights/train-4.pt}"
if [ ! -f "$CHECKPOINT" ]; then echo "ERROR: checkpoint not found: $CHECKPOINT"; exit 2; fi

# Full Text/Pose Context RAG.
export EDGE_ENABLE_TEXT_CONTEXT_RAG="${EDGE_ENABLE_TEXT_CONTEXT_RAG:-1}"
export EDGE_TEXT_CONTEXT_DIM="${EDGE_TEXT_CONTEXT_DIM:-512}"
export EDGE_TEXT_CONTEXT_MAX_POSE_TOKENS="${EDGE_TEXT_CONTEXT_MAX_POSE_TOKENS:-64}"
export EDGE_RAG_CONTEXT_MAX_LEN="${EDGE_RAG_CONTEXT_MAX_LEN:-45}"
export EDGE_TEXT_CONTEXT_DROP_PROB="${EDGE_TEXT_CONTEXT_DROP_PROB:-0.0}"

# Text-guided semantic re-ranking.
export EDGE_TEXT_BRIDGE_WEIGHT="${EDGE_TEXT_BRIDGE_WEIGHT:-0.30}"
export EDGE_TEXT_QUERY="${EDGE_TEXT_QUERY:-敦煌舞，飞天风格，高能量，上肢大幅舒展，流动转身，空间展开，亮相收束}"
export EDGE_TEXT_BRIDGE_MODEL="${EDGE_TEXT_BRIDGE_MODEL:-BAAI/bge-small-zh-v1.5}"
export EDGE_TEXT_BRIDGE_DEVICE="${EDGE_TEXT_BRIDGE_DEVICE:-cpu}"
export EDGE_TEXT_BRIDGE_FALLBACK_DIM="${EDGE_TEXT_BRIDGE_FALLBACK_DIM:-512}"

# Existing V9/V10 controls.
export EDGE_ENABLE_RAG_SUMMARY_TOKEN=1
export EDGE_RAG_SUMMARY_MODE="${EDGE_RAG_SUMMARY_MODE:-mean}"
export EDGE_RAG_SUMMARY_DIM=7
export EDGE_TRAJECTORY_REP="${EDGE_TRAJECTORY_REP:-relative_abs_vel}"
export EDGE_AUDIO_ENERGY_AS_COND="${EDGE_AUDIO_ENERGY_AS_COND:-1}"
export EDGE_MUSIC_TENSION_AS_ENERGY="${EDGE_MUSIC_TENSION_AS_ENERGY:-1}"
export EDGE_ENERGY_CFG_SCALE="${EDGE_ENERGY_CFG_SCALE:-0.50}"
export EDGE_CONTEXT_RAG_ENHANCE="${EDGE_CONTEXT_RAG_ENHANCE:-1}"
export EDGE_CONTEXT_RAG_SCALE="${EDGE_CONTEXT_RAG_SCALE:-0.50}"
export EDGE_UNIT_SOFT_PRIOR="${EDGE_UNIT_SOFT_PRIOR:-1}"
export EDGE_UNIT_PRIOR_DCT="${EDGE_UNIT_PRIOR_DCT:-1}"
export EDGE_UNIT_PRIOR_LOW_FREQ_K="${EDGE_UNIT_PRIOR_LOW_FREQ_K:-4}"
export EDGE_UNIT_PRIOR_FEATURES="${EDGE_UNIT_PRIOR_FEATURES:-upper}"
export EDGE_UNIT_PRIOR_STRENGTH="${EDGE_UNIT_PRIOR_STRENGTH:-0.012}"
export EDGE_V10_SEARCH_METHOD="${EDGE_V10_SEARCH_METHOD:-beam}"
export EDGE_V10_TOP_K="${EDGE_V10_TOP_K:-64}"
export EDGE_V10_BEAM_WIDTH="${EDGE_V10_BEAM_WIDTH:-8}"
export EDGE_V10_OUT_PREFIX="${EDGE_V10_OUT_PREFIX:-output/v10_eval/v10_text_context_step4_w${EDGE_TEXT_BRIDGE_WEIGHT}}"
export OUT_PATH="${OUT_PATH:-${EDGE_V10_OUT_PREFIX}.npy}"
CHECKPOINT="$CHECKPOINT" bash scripts/run_v10_step4_auto_multiunit.sh 2>&1 | tee "logs/v10_text_context_step4_w${EDGE_TEXT_BRIDGE_WEIGHT}.log"
