#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
export PYTHONPATH="$PWD:${PYTHONPATH:-}"
export V46_ENABLE_TRUE_IK=1
export V46_DEVICE="${V46_DEVICE:-cuda}"
export V46_SOURCE_GROUP_MODE="${V46_SOURCE_GROUP_MODE:-filename}"
export V46_FILENAME_SEMANTIC_ENABLE="${V46_FILENAME_SEMANTIC_ENABLE:-1}"
export V46_ENABLE_ROOT_Y_PHYSICS="${V46_ENABLE_ROOT_Y_PHYSICS:-1}"
export V46_ROOT_Y_MIN_FLIGHT_FRAMES="${V46_ROOT_Y_MIN_FLIGHT_FRAMES:-3}"
export V46_ROOT_Y_MAX_FLIGHT_SECONDS="${V46_ROOT_Y_MAX_FLIGHT_SECONDS:-1.2}"
export V46_ROOT_Y_DAMPING_MAX_SECONDS="${V46_ROOT_Y_DAMPING_MAX_SECONDS:-0.28}"
export V46_IK_CHUNK_OVERLAP="${V46_IK_CHUNK_OVERLAP:-24}"
CFG="configs/v46_motionrag_diff_config.json"
INPUT="${1:?usage: bash scripts/run_v43_true_ik_on_existing_motion.sh input.npy [output.npy]}"
OUTPUT="${2:-${INPUT%.npy}_v43_TRUE_LB_IK.npy}"
JSON="${OUTPUT%.npy}.v43_true_ik.json"
python tools/v46_motionrag_diff.py --config "$CFG" ik --input "$INPUT" --output "$OUTPUT" --json "$JSON"
echo "[V43 TRUE IK] $OUTPUT"
echo "[REPORT]      $JSON"
