#!/usr/bin/env bash
set -euo pipefail

cd /home/disk/lsm/storage/EDGE

export EDGE_ROOT=/home/disk/lsm/storage/EDGE
export EDGE_ENV=/home/disk/lsm/conda_envs/edge
export PATH="$EDGE_ENV/bin:$PATH"
export PYTHONPATH="$EDGE_ROOT${PYTHONPATH:+:$PYTHONPATH}"
export CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
export PYTHONUNBUFFERED=1
export OMP_NUM_THREADS=${OMP_NUM_THREADS:-8}
export MKL_NUM_THREADS=${MKL_NUM_THREADS:-8}
mkdir -p output

source scripts/v39_contact_stability_env.sh

# Inherited from the successful V35/V36 runs.
export V26_ROUTER_CKPT="${V26_ROUTER_CKPT:-output/v21_music_router_985songs_20260605_154801/seed_20260607/checkpoints/best.pt}"
export V26_V23_CKPT="${V26_V23_CKPT:-output/v23_v2_5_continuous_gate_20260607_004858/seed_20260612/stage2_timewarp/checkpoints/best.pt}"
export V26_PLANNER_CKPT="${V26_PLANNER_CKPT:-output/v26_music_dominant_whole_song_planner_985/checkpoints/best.pt}"

export V26_INDEX_JSON="${V26_INDEX_JSON:-data/v34_shared_event_index.json}"
export V26_DURATION_INDEX_NPZ="${V26_DURATION_INDEX_NPZ:-data/v26_music_dominant_duration_index.npz}"
export V33_EVENT_CONTACT_CACHE="${V33_EVENT_CONTACT_CACHE:-data/v34_source_aware/v33_event_contact_cache_source_aware.npz}"

export V34_SOURCE_AWARE_REBUILD=${V34_SOURCE_AWARE_REBUILD:-1}
export V34_SOURCE_AWARE_REBUILD_HIERARCHY=${V34_SOURCE_AWARE_REBUILD_HIERARCHY:-1}
export V34_SOURCE_AWARE_RAG=${V34_SOURCE_AWARE_RAG:-1}

export V34_SOURCE_CAP_PER_SOURCE_UID=${V34_SOURCE_CAP_PER_SOURCE_UID:-64}
export V34_SOURCE_CATEGORY_CAP_FACTOR=${V34_SOURCE_CATEGORY_CAP_FACTOR:-1.35}
export V34_SOURCE_REPEAT_CAP_FACTOR=${V34_SOURCE_REPEAT_CAP_FACTOR:-1.60}
export V34_SOURCE_DANCER_CAP_FACTOR=${V34_SOURCE_DANCER_CAP_FACTOR:-1.50}

export V34_BOUNDARY_COMPAT=${V34_BOUNDARY_COMPAT:-1}
export V34_COMPAT_DENSE_SCORE=${V34_COMPAT_DENSE_SCORE:-1}
export V34_BOUNDARY_INPAINT=${V34_BOUNDARY_INPAINT:-1}
export V34_LATENT_SNIPPET_BLEND=${V34_LATENT_SNIPPET_BLEND:-1}

export V34_RHYTHM_DEGRADATION_PENALTY=${V34_RHYTHM_DEGRADATION_PENALTY:-1}
export V34_RHYTHM_WEIGHT=${V34_RHYTHM_WEIGHT:-1.20}
export V34_STATIC_STREAK_ALLOW=${V34_STATIC_STREAK_ALLOW:-1}
export V34_STREAK_PENALTY_WEIGHT=${V34_STREAK_PENALTY_WEIGHT:-3.00}

export V34_MOTION_QUALITY_POSTPROCESS=${V34_MOTION_QUALITY_POSTPROCESS:-1}

export V34_TRAIN=${V34_TRAIN:-1}
export V34_AE_EPOCHS=${V34_AE_EPOCHS:-180}
export V34_CONTACT_EPOCHS=${V34_CONTACT_EPOCHS:-70}
export V34_DIFFUSION_EPOCHS=${V34_DIFFUSION_EPOCHS:-280}
export V34_AE_PATIENCE=${V34_AE_PATIENCE:-45}
export V34_CONTACT_PATIENCE=${V34_CONTACT_PATIENCE:-25}
export V34_DIFFUSION_PATIENCE=${V34_DIFFUSION_PATIENCE:-60}
export V34_AE_BATCH_SIZE=${V34_AE_BATCH_SIZE:-36}
export V34_CONTACT_BATCH_SIZE=${V34_CONTACT_BATCH_SIZE:-28}
export V34_LATENT_BATCH_SIZE=${V34_LATENT_BATCH_SIZE:-160}
export V34_AE_LR=${V34_AE_LR:-1.2e-4}
export V34_CONTACT_LR=${V34_CONTACT_LR:-3e-5}
export V34_DIFFUSION_LR=${V34_DIFFUSION_LR:-1.8e-4}

export RUN_ID="${RUN_ID:-v39_contact_stable_source_aware_full_train_$(date +%Y%m%d_%H%M%S)}"
export RUN_ROOT="${RUN_ROOT:-output/$RUN_ID}"
echo "$RUN_ROOT" > output/LATEST_V39_CONTACT_STABLE_FULL_TRAIN.txt

echo "[RUN_ROOT] $RUN_ROOT"
echo "[CHECK] V26_INDEX_JSON=$V26_INDEX_JSON"
echo "[CHECK] V26_DURATION_INDEX_NPZ=$V26_DURATION_INDEX_NPZ"
echo "[CHECK] V33_EVENT_CONTACT_CACHE=$V33_EVENT_CONTACT_CACHE"
echo "[CHECK] V26_ROUTER_CKPT=$V26_ROUTER_CKPT"
echo "[CHECK] V26_V23_CKPT=$V26_V23_CKPT"
echo "[CHECK] V26_PLANNER_CKPT=$V26_PLANNER_CKPT"

[[ -f "$V26_INDEX_JSON" ]] || { echo "[ERROR] missing V26_INDEX_JSON"; exit 2; }
[[ -f "$V26_DURATION_INDEX_NPZ" ]] || { echo "[ERROR] missing V26_DURATION_INDEX_NPZ"; exit 2; }
[[ -f "$V33_EVENT_CONTACT_CACHE" ]] || { echo "[ERROR] missing V33_EVENT_CONTACT_CACHE"; exit 2; }
[[ -f "$V26_ROUTER_CKPT" ]] || { echo "[ERROR] missing V26_ROUTER_CKPT"; exit 2; }
[[ -f "$V26_V23_CKPT" ]] || { echo "[ERROR] missing V26_V23_CKPT"; exit 2; }

bash scripts/launch_v34_source_aware_rag.sh
