#!/usr/bin/env bash
# Source this file before V34/V38/V39 training or reprocessing.
# It keeps global motion unsmoothed and only stabilizes contact + IK side effects.

export V39_CONTACT_STABILITY=1

# Contact confidence + hysteresis.  This removes 1-5 frame pseudo-contact holes.
export V39_CONTACT_HYSTERESIS=${V39_CONTACT_HYSTERESIS:-1}
export V39_CONTACT_ON_THRESHOLD=${V39_CONTACT_ON_THRESHOLD:-0.58}
export V39_CONTACT_OFF_THRESHOLD=${V39_CONTACT_OFF_THRESHOLD:-0.42}
export V39_CONTACT_LABEL_WEIGHT=${V39_CONTACT_LABEL_WEIGHT:-0.45}
export V39_CONTACT_HEIGHT_WEIGHT=${V39_CONTACT_HEIGHT_WEIGHT:-0.30}
export V39_CONTACT_SPEED_WEIGHT=${V39_CONTACT_SPEED_WEIGHT:-0.25}
export V38_CONTACT_DENOISE=${V38_CONTACT_DENOISE:-1}
export V38_CONTACT_MEDIAN_SIZE=${V38_CONTACT_MEDIAN_SIZE:-5}
export V38_CONTACT_CLOSE_HOLES=${V38_CONTACT_CLOSE_HOLES:-7}
export V38_CONTACT_OPEN_SPIKES=${V38_CONTACT_OPEN_SPIKES:-4}

# SmoothStep footplant root solver.
export V39_FOOTPLANT_SOLVER=${V39_FOOTPLANT_SOLVER:-1}
export V38_CONTACT_LOCK_BLEND_FRAMES=${V38_CONTACT_LOCK_BLEND_FRAMES:-6}
export V34_CONTACT_LOCK_POSTPROCESS=${V34_CONTACT_LOCK_POSTPROCESS:-1}
export V34_CONTACT_LOCK_THRESHOLD=${V34_CONTACT_LOCK_THRESHOLD:-0.65}
export V34_CONTACT_LOCK_STRENGTH=${V34_CONTACT_LOCK_STRENGTH:-0.88}
export V34_CONTACT_LOCK_SMOOTH_WINDOW=${V34_CONTACT_LOCK_SMOOTH_WINDOW:-11}
export V34_CONTACT_LOCK_MAX_ROOT_CORRECTION=${V34_CONTACT_LOCK_MAX_ROOT_CORRECTION:-0.20}
export V39_ROOT_CORR_MAX_STEP=${V39_ROOT_CORR_MAX_STEP:-0.026}
export V39_ROOT_CORR_MAX_ACCEL=${V39_ROOT_CORR_MAX_ACCEL:-0.012}
export V39_ROOT_CORR_LIMIT_PASSES=${V39_ROOT_CORR_LIMIT_PASSES:-2}
export V39_SUPPORT_ROOT_VELOCITY_DAMPING=${V39_SUPPORT_ROOT_VELOCITY_DAMPING:-0.10}

# Root-Y and floor safety.
export V34_ROOT_Y_PHYSICS=${V34_ROOT_Y_PHYSICS:-1}
export V34_FLOOR_CLEARANCE_POSTPROCESS=${V34_FLOOR_CLEARANCE_POSTPROCESS:-1}
export V34_FLOOR_SUPPORT_DAMPING=${V34_FLOOR_SUPPORT_DAMPING:-0.25}

# Collision IK: slightly stronger temporal regularization than V38.
export V39_COLLISION_STEPS=${V39_COLLISION_STEPS:-20}
export V39_COLLISION_TEMPORAL_WEIGHT=${V39_COLLISION_TEMPORAL_WEIGHT:-0.05}

# Residual-only low-pass on IK-sensitive joints.  Do not use global smoothing.
export V34_OUTPUT_SMOOTH=${V34_OUTPUT_SMOOTH:-0}
export V38_BUTTERWORTH_FILTER=${V38_BUTTERWORTH_FILTER:-1}
export V39_BUTTERWORTH_RESIDUAL_ONLY=${V39_BUTTERWORTH_RESIDUAL_ONLY:-1}
export V38_BUTTERWORTH_CUTOFF_HZ=${V38_BUTTERWORTH_CUTOFF_HZ:-4.2}
export V38_BUTTERWORTH_ORDER=${V38_BUTTERWORTH_ORDER:-2}
export V38_BUTTERWORTH_STRENGTH=${V38_BUTTERWORTH_STRENGTH:-0.78}
export V38_BUTTERWORTH_JOINTS=${V38_BUTTERWORTH_JOINTS:-lelbow,relbow,lwrist,rwrist,lhand,rhand,lshoulder,rshoulder}

echo "[V39] contact stability env loaded"
