#!/usr/bin/env bash
# V39B: stricter contact confidence + footplant segment gate + safe residual low-pass rollback.

export V39_CONTACT_STABILITY=1

# Stricter contact confidence: avoid classifying moving feet as support.
export V39_CONTACT_HYSTERESIS=${V39_CONTACT_HYSTERESIS:-1}
export V39_CONTACT_ON_THRESHOLD=${V39_CONTACT_ON_THRESHOLD:-0.66}
export V39_CONTACT_OFF_THRESHOLD=${V39_CONTACT_OFF_THRESHOLD:-0.50}
export V39_CONTACT_LABEL_WEIGHT=${V39_CONTACT_LABEL_WEIGHT:-0.30}
export V39_CONTACT_HEIGHT_WEIGHT=${V39_CONTACT_HEIGHT_WEIGHT:-0.40}
export V39_CONTACT_SPEED_WEIGHT=${V39_CONTACT_SPEED_WEIGHT:-0.30}
export V34_KIN_CONTACT_HEIGHT=${V34_KIN_CONTACT_HEIGHT:-0.032}
export V34_KIN_CONTACT_SPEED=${V34_KIN_CONTACT_SPEED:-0.020}
export V38_CONTACT_DENOISE=${V38_CONTACT_DENOISE:-1}
export V38_CONTACT_MEDIAN_SIZE=${V38_CONTACT_MEDIAN_SIZE:-5}
export V38_CONTACT_CLOSE_HOLES=${V38_CONTACT_CLOSE_HOLES:-5}
export V38_CONTACT_OPEN_SPIKES=${V38_CONTACT_OPEN_SPIKES:-6}
export V34_MIN_CONTACT_FRAMES=${V34_MIN_CONTACT_FRAMES:-10}

# Reject false long footplants.  This is the main V39B fix for your current log.
export V39_REJECT_MOVING_FOOTPLANTS=${V39_REJECT_MOVING_FOOTPLANTS:-1}
export V39_MAX_FOOTPLANT_SEGMENT_ERROR=${V39_MAX_FOOTPLANT_SEGMENT_ERROR:-0.055}
export V39_MAX_FOOTPLANT_SEGMENT_P95=${V39_MAX_FOOTPLANT_SEGMENT_P95:-0.110}
export V39_MAX_FOOTPLANT_SEGMENT_FRAMES=${V39_MAX_FOOTPLANT_SEGMENT_FRAMES:-120}

# Gentler SmoothStep footplant solver.
export V39_FOOTPLANT_SOLVER=${V39_FOOTPLANT_SOLVER:-1}
export V38_CONTACT_LOCK_BLEND_FRAMES=${V38_CONTACT_LOCK_BLEND_FRAMES:-8}
export V34_CONTACT_LOCK_POSTPROCESS=${V34_CONTACT_LOCK_POSTPROCESS:-1}
export V34_CONTACT_LOCK_THRESHOLD=${V34_CONTACT_LOCK_THRESHOLD:-0.65}
export V34_CONTACT_LOCK_STRENGTH=${V34_CONTACT_LOCK_STRENGTH:-0.78}
export V34_CONTACT_LOCK_SMOOTH_WINDOW=${V34_CONTACT_LOCK_SMOOTH_WINDOW:-11}
export V34_CONTACT_LOCK_MAX_ROOT_CORRECTION=${V34_CONTACT_LOCK_MAX_ROOT_CORRECTION:-0.12}
export V39_ROOT_CORR_MAX_STEP=${V39_ROOT_CORR_MAX_STEP:-0.016}
export V39_ROOT_CORR_MAX_ACCEL=${V39_ROOT_CORR_MAX_ACCEL:-0.006}
export V39_ROOT_CORR_LIMIT_PASSES=${V39_ROOT_CORR_LIMIT_PASSES:-2}
export V39_SUPPORT_ROOT_VELOCITY_DAMPING=${V39_SUPPORT_ROOT_VELOCITY_DAMPING:-0.04}

# Root-Y and floor safety: use lower floor quantile to avoid over-estimated floor.
export V34_ROOT_Y_PHYSICS=${V34_ROOT_Y_PHYSICS:-1}
export V34_FLOOR_QUANTILE=${V34_FLOOR_QUANTILE:-0.03}
export V34_FLOOR_CLEARANCE_POSTPROCESS=${V34_FLOOR_CLEARANCE_POSTPROCESS:-1}
export V34_FLOOR_MARGIN=${V34_FLOOR_MARGIN:-0.003}
export V34_FLOOR_STRENGTH=${V34_FLOOR_STRENGTH:-0.90}
export V34_FLOOR_SMOOTH_WINDOW=${V34_FLOOR_SMOOTH_WINDOW:-7}
export V34_FLOOR_MAX_LIFT=${V34_FLOOR_MAX_LIFT:-0.18}
export V34_FLOOR_SUPPORT_DAMPING=${V34_FLOOR_SUPPORT_DAMPING:-0.10}

# Disable collision IK by default; previous audit showed it did not reduce bad frames and may add jitter.
export V39_COLLISION_IK=${V39_COLLISION_IK:-0}
export V39_COLLISION_STEPS=${V39_COLLISION_STEPS:-12}
export V39_COLLISION_TEMPORAL_WEIGHT=${V39_COLLISION_TEMPORAL_WEIGHT:-0.08}

# Residual-only low-pass, wrist/hand only, with automatic rollback if jerk worsens.
export V34_OUTPUT_SMOOTH=${V34_OUTPUT_SMOOTH:-0}
export V38_BUTTERWORTH_FILTER=${V38_BUTTERWORTH_FILTER:-1}
export V39_BUTTERWORTH_RESIDUAL_ONLY=${V39_BUTTERWORTH_RESIDUAL_ONLY:-1}
export V39_BUTTERWORTH_ROLLBACK_IF_WORSE=${V39_BUTTERWORTH_ROLLBACK_IF_WORSE:-1}
export V39_BUTTERWORTH_MAX_JERK_WORSEN=${V39_BUTTERWORTH_MAX_JERK_WORSEN:-1.15}
export V39_BUTTERWORTH_MAX_HAND_WORSEN=${V39_BUTTERWORTH_MAX_HAND_WORSEN:-1.15}
export V38_BUTTERWORTH_CUTOFF_HZ=${V38_BUTTERWORTH_CUTOFF_HZ:-3.8}
export V38_BUTTERWORTH_ORDER=${V38_BUTTERWORTH_ORDER:-2}
export V38_BUTTERWORTH_STRENGTH=${V38_BUTTERWORTH_STRENGTH:-0.35}
export V38_BUTTERWORTH_JOINTS=${V38_BUTTERWORTH_JOINTS:-lwrist,rwrist,lhand,rhand}

echo "[V39B] footplant-gated contact stability env loaded"
