#!/usr/bin/env bash
# V40B native-floor source pruning + forced reroute environment.

export EDGE_ROOT="${EDGE_ROOT:-/home/disk/lsm/storage/EDGE}"
export PYTHONPATH="${EDGE_ROOT}${PYTHONPATH:+:$PYTHONPATH}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONUNBUFFERED=1

# Source pruning: relative native floor penetration, not raw absolute Y.
export V40B_NATIVE_FLOOR_MODE="${V40B_NATIVE_FLOOR_MODE:-remove}"
export V40B_NATIVE_FLOOR_QUANTILE="${V40B_NATIVE_FLOOR_QUANTILE:-0.05}"
export V40B_NATIVE_FLOOR_MARGIN="${V40B_NATIVE_FLOOR_MARGIN:-0.006}"
export V40B_NATIVE_FLOOR_TOLERANCE_M="${V40B_NATIVE_FLOOR_TOLERANCE_M:-0.040}"
export V40B_NATIVE_FLOOR_SOFT_THRESHOLD="${V40B_NATIVE_FLOOR_SOFT_THRESHOLD:-0.055}"
export V40B_NATIVE_FLOOR_REMOVE_THRESHOLD="${V40B_NATIVE_FLOOR_REMOVE_THRESHOLD:-0.080}"
export V40B_NATIVE_FLOOR_PENALTY_WEIGHT="${V40B_NATIVE_FLOOR_PENALTY_WEIGHT:-18.0}"
export V40B_MAX_REMOVE_FRACTION="${V40B_MAX_REMOVE_FRACTION:-0.35}"
export V40B_MIN_REMAINING_EVENTS="${V40B_MIN_REMAINING_EVENTS:-128}"
export V40B_MISSING_POLICY="${V40B_MISSING_POLICY:-keep}"

# Keep V40 retrieval penalty active for survivors.
export V40_NATIVE_FLOOR_PENALTY="${V40_NATIVE_FLOOR_PENALTY:-1}"
export V40_NATIVE_FLOOR_TOLERANCE_M="${V40_NATIVE_FLOOR_TOLERANCE_M:-0.035}"
export V40_NATIVE_FLOOR_PENALTY_WEIGHT="${V40_NATIVE_FLOOR_PENALTY_WEIGHT:-18.0}"
export V40_NATIVE_FLOOR_QUANTILE="${V40_NATIVE_FLOOR_QUANTILE:-0.05}"
export V40_NATIVE_FLOOR_MARGIN="${V40_NATIVE_FLOOR_MARGIN:-0.006}"

# Larger search after pruning so V34 can reroute.
export V26_BEAM_SIZE="${V26_BEAM_SIZE:-72}"
export V26_CANDIDATE_TOP_K="${V26_CANDIDATE_TOP_K:-1024}"
export V34_WARP_PREFILTER_TOP_K="${V34_WARP_PREFILTER_TOP_K:-768}"
export V32_CANDIDATES="${V32_CANDIDATES:-10}"

# Prevent static fallback and repeated poisoned families.
export V34_SOURCE_AWARE_RAG="${V34_SOURCE_AWARE_RAG:-1}"
export V34_SOURCE_AWARE_WINDOW="${V34_SOURCE_AWARE_WINDOW:-10}"
export V34_SOURCE_AWARE_WEIGHT="${V34_SOURCE_AWARE_WEIGHT:-1.15}"
export V34_SOURCE_UID_REPEAT_WEIGHT="${V34_SOURCE_UID_REPEAT_WEIGHT:-3.00}"
export V34_DANCER_CATEGORY_REPEAT_WEIGHT="${V34_DANCER_CATEGORY_REPEAT_WEIGHT:-1.45}"
export V34_RHYTHM_DEGRADATION_PENALTY="${V34_RHYTHM_DEGRADATION_PENALTY:-1}"
export V34_RHYTHM_WEIGHT="${V34_RHYTHM_WEIGHT:-1.35}"
export V34_STATIC_STREAK_ALLOW="${V34_STATIC_STREAK_ALLOW:-1}"
export V34_STREAK_PENALTY_WEIGHT="${V34_STREAK_PENALTY_WEIGHT:-3.50}"

# V40 postprocess for rerouted raw output.  Conservative: source pruning should
# lower native penetration before postprocess.
export V34_MOTION_QUALITY_POSTPROCESS="${V34_MOTION_QUALITY_POSTPROCESS:-1}"
export V34_ROOT_Y_PHYSICS="${V34_ROOT_Y_PHYSICS:-1}"
export V34_CONTACT_LOCK_POSTPROCESS="${V34_CONTACT_LOCK_POSTPROCESS:-1}"
export V34_FLOOR_CLEARANCE_POSTPROCESS="${V34_FLOOR_CLEARANCE_POSTPROCESS:-1}"
export V38_BUTTERWORTH_FILTER="${V38_BUTTERWORTH_FILTER:-1}"

export V40_FLOOR_AWARE_LEG_IK="${V40_FLOOR_AWARE_LEG_IK:-1}"
export V40_FLOOR_IK_STEPS="${V40_FLOOR_IK_STEPS:-35}"
export V40_FLOOR_IK_LR="${V40_FLOOR_IK_LR:-0.012}"
export V40_FLOOR_IK_FLOOR_WEIGHT="${V40_FLOOR_IK_FLOOR_WEIGHT:-28.0}"
export V40_FLOOR_IK_ROOT_WEIGHT="${V40_FLOOR_IK_ROOT_WEIGHT:-0.04}"
export V40_FLOOR_IK_ROT_WEIGHT="${V40_FLOOR_IK_ROT_WEIGHT:-0.45}"
export V40_FLOOR_IK_TEMPORAL_WEIGHT="${V40_FLOOR_IK_TEMPORAL_WEIGHT:-0.08}"
export V40_FLOOR_IK_ANATOMY_WEIGHT="${V40_FLOOR_IK_ANATOMY_WEIGHT:-24.0}"
export V40_FLOOR_IK_MAX_ROOT_DELTA="${V40_FLOOR_IK_MAX_ROOT_DELTA:-0.16}"
export V40_FLOOR_IK_LOWER_JOINTS="${V40_FLOOR_IK_LOWER_JOINTS:-lhip,rhip,lknee,rknee,lankle,rankle,ltoes,rtoes}"

export V40_ANKLE_PITCH_CLAMP="${V40_ANKLE_PITCH_CLAMP:-1}"
export V40_ANKLE_CLAMP_MAX_DEG="${V40_ANKLE_CLAMP_MAX_DEG:-28.0}"
export V40_ANKLE_CLAMP_CONTACT_MAX="${V40_ANKLE_CLAMP_CONTACT_MAX:-0.45}"

unset V41_BEAT_SUPPORT_STABILIZER || true
unset V41_BEAT_DECOUPLED_SUPPORT_STABILIZER || true
unset V41_ROOT_XZ_FILTER_STRENGTH || true
unset V41_RELOCK_STRENGTH || true
unset V41_SUPPORT_LOWER_STRENGTH || true

echo "[V40B] native-floor source pruning + reroute env loaded"
