#!/usr/bin/env bash
# V41.2 FK-verified native-floor-aware planner environment.
# Planner-level barrier only; does NOT enable V41 beat-support stabilizer.

export EDGE_ROOT="${EDGE_ROOT:-/home/disk/lsm/storage/EDGE}"
export PYTHONPATH="${EDGE_ROOT}${PYTHONPATH:+:$PYTHONPATH}"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONUNBUFFERED=1

# --- Core V41/V41.2 planner barrier ---
export V41_NATIVE_FLOOR_PLANNER="${V41_NATIVE_FLOOR_PLANNER:-1}"
export V41_NATIVE_FLOOR_HARD_MASK="${V41_NATIVE_FLOOR_HARD_MASK:-1}"
export V41_NATIVE_FLOOR_RELAX_ON_EMPTY="${V41_NATIVE_FLOOR_RELAX_ON_EMPTY:-1}"
export V41_NATIVE_FLOOR_VERBOSE="${V41_NATIVE_FLOOR_VERBOSE:-1}"

# Relative penetration thresholds.  Do NOT use absolute raw 151D channels.
export V41_NATIVE_FLOOR_TAU_SAFE_M="${V41_NATIVE_FLOOR_TAU_SAFE_M:-0.012}"
export V41_NATIVE_FLOOR_TAU_DEAD_M="${V41_NATIVE_FLOOR_TAU_DEAD_M:-0.052}"
export V41_NATIVE_FLOOR_ALPHA="${V41_NATIVE_FLOOR_ALPHA:-9.0}"
export V41_NATIVE_FLOOR_BETA="${V41_NATIVE_FLOOR_BETA:-2.5}"
export V41_NATIVE_FLOOR_PENALTY_CAP="${V41_NATIVE_FLOOR_PENALTY_CAP:-18.0}"
export V41_NATIVE_FLOOR_DEAD_RESCUE_PENALTY="${V41_NATIVE_FLOOR_DEAD_RESCUE_PENALTY:-25.0}"
export V41_NATIVE_FLOOR_QUANTILE="${V41_NATIVE_FLOOR_QUANTILE:-0.05}"
export V41_NATIVE_FLOOR_MARGIN="${V41_NATIVE_FLOOR_MARGIN:-0.006}"
export V41_NATIVE_FLOOR_FOOT_JOINTS="${V41_NATIVE_FLOOR_FOOT_JOINTS:-7,8,10,11}"

# Missing feature policy: never silently treat missing physics as safe.
export V41_NATIVE_FLOOR_MISSING_POLICY="${V41_NATIVE_FLOOR_MISSING_POLICY:-penalize}"
export V41_NATIVE_FLOOR_MISSING_PENETRATION_M="${V41_NATIVE_FLOOR_MISSING_PENETRATION_M:-${V41_NATIVE_FLOOR_TAU_DEAD_M:-0.052}}"
export V41_NATIVE_FLOOR_FAIL_ON_MISSING="${V41_NATIVE_FLOOR_FAIL_ON_MISSING:-1}"
export V41_NATIVE_FLOOR_MAX_MISSING_FRACTION="${V41_NATIVE_FLOOR_MAX_MISSING_FRACTION:-0.01}"

# Keep V40 soft prior as a weak auxiliary prior.
export V40_NATIVE_FLOOR_PENALTY="${V40_NATIVE_FLOOR_PENALTY:-1}"
export V40_NATIVE_FLOOR_TOLERANCE_M="${V40_NATIVE_FLOOR_TOLERANCE_M:-0.04}"
export V40_NATIVE_FLOOR_PENALTY_WEIGHT="${V40_NATIVE_FLOOR_PENALTY_WEIGHT:-8.0}"

# Avoid accidental V41 beat-support pollution.
unset V41_BEAT_SUPPORT_STABILIZER || true
unset V41_BEAT_DECOUPLED_SUPPORT_STABILIZER || true
unset V41_ROOT_XZ_FILTER_STRENGTH || true
unset V41_RELOCK_STRENGTH || true
unset V41_SUPPORT_LOWER_STRENGTH || true

# Default checkpoints discovered from successful runs.
export V26_ROUTER_CKPT="${V26_ROUTER_CKPT:-output/v21_music_router_985songs_20260605_154801/seed_20260607/checkpoints/best.pt}"
export V26_V23_CKPT="${V26_V23_CKPT:-output/v23_v2_5_continuous_gate_20260607_004858/seed_20260612/stage2_timewarp/checkpoints/best.pt}"
export V26_PLANNER_CKPT="${V26_PLANNER_CKPT:-output/v26_music_dominant_whole_song_planner_985/checkpoints/best.pt}"
export V27_TRANSITION_DIFFUSION_CKPT="${V27_TRANSITION_DIFFUSION_CKPT:-output/v33_event_contact_20260611_204533/v32_contact_inr_training/checkpoints/best.pt}"

# Source-aware event index.
export V41_SOURCE_INDEX_JSON="${V41_SOURCE_INDEX_JSON:-data/v34_source_aware/v34_shared_event_index_source_aware.json}"
export V41_SOURCE_INDEX_NPZ="${V41_SOURCE_INDEX_NPZ:-data/v34_source_aware/v34_shared_event_index_source_aware.npz}"

# Generation defaults.
export V26_MIN_TIME_WARP="${V26_MIN_TIME_WARP:-0.82}"
export V26_MAX_TIME_WARP="${V26_MAX_TIME_WARP:-1.30}"
export V26_BEAM_SIZE="${V26_BEAM_SIZE:-64}"
export V26_CANDIDATE_TOP_K="${V26_CANDIDATE_TOP_K:-1024}"
export V34_WARP_PREFILTER_TOP_K="${V34_WARP_PREFILTER_TOP_K:-1024}"
export V27_TRANSITION_DIFFUSION="${V27_TRANSITION_DIFFUSION:-1}"
export V32_INR_TRUST="${V32_INR_TRUST:-0.25}"
export V32_INFERENCE_STEPS="${V32_INFERENCE_STEPS:-40}"

# V40 postprocess defaults after V41 planner reroute.
export V34_MOTION_QUALITY_POSTPROCESS="${V34_MOTION_QUALITY_POSTPROCESS:-1}"
export V34_ROOT_Y_PHYSICS="${V34_ROOT_Y_PHYSICS:-1}"
export V34_CONTACT_LOCK="${V34_CONTACT_LOCK:-1}"
export V34_FLOOR_CLEARANCE="${V34_FLOOR_CLEARANCE:-1}"
export V38_BUTTERWORTH_FILTER="${V38_BUTTERWORTH_FILTER:-1}"
export V40_FLOOR_AWARE_LEG_IK="${V40_FLOOR_AWARE_LEG_IK:-1}"
export V40_ANKLE_PITCH_CLAMP="${V40_ANKLE_PITCH_CLAMP:-1}"
export V34_FLOOR_MAX_LIFT="${V34_FLOOR_MAX_LIFT:-0.36}"
export V40_FLOOR_IK_STEPS="${V40_FLOOR_IK_STEPS:-55}"
export V40_FLOOR_IK_LR="${V40_FLOOR_IK_LR:-0.010}"
export V40_FLOOR_IK_FLOOR_WEIGHT="${V40_FLOOR_IK_FLOOR_WEIGHT:-42.0}"
export V40_FLOOR_IK_ROOT_WEIGHT="${V40_FLOOR_IK_ROOT_WEIGHT:-0.025}"
export V40_FLOOR_IK_ROT_WEIGHT="${V40_FLOOR_IK_ROT_WEIGHT:-0.32}"
export V40_FLOOR_IK_TEMPORAL_WEIGHT="${V40_FLOOR_IK_TEMPORAL_WEIGHT:-0.09}"
export V40_FLOOR_IK_ANATOMY_WEIGHT="${V40_FLOOR_IK_ANATOMY_WEIGHT:-28.0}"
export V40_FLOOR_IK_MAX_ROOT_DELTA="${V40_FLOOR_IK_MAX_ROOT_DELTA:-0.22}"
export V40_FLOOR_IK_CONTEXT_FRAMES="${V40_FLOOR_IK_CONTEXT_FRAMES:-5}"
export V40_FLOOR_IK_LOWER_JOINTS="${V40_FLOOR_IK_LOWER_JOINTS:-lhip,rhip,lknee,rknee,lankle,rankle,ltoes,rtoes}"
export V40_ANKLE_CLAMP_MAX_DEG="${V40_ANKLE_CLAMP_MAX_DEG:-38.0}"
export V40_ANKLE_CLAMP_CONTACT_MAX="${V40_ANKLE_CLAMP_CONTACT_MAX:-0.60}"
export V40_ANKLE_CLAMP_TRIGGER_M="${V40_ANKLE_CLAMP_TRIGGER_M:-0.008}"
export V34_CONTACT_LOCK_STRENGTH="${V34_CONTACT_LOCK_STRENGTH:-0.70}"
export V39_ROOT_CORR_MAX_STEP="${V39_ROOT_CORR_MAX_STEP:-0.009}"
export V39_ROOT_CORR_MAX_ACCEL="${V39_ROOT_CORR_MAX_ACCEL:-0.003}"
export V39_SUPPORT_ROOT_VELOCITY_DAMPING="${V39_SUPPORT_ROOT_VELOCITY_DAMPING:-0.04}"

echo "[V41.2] FK-verified native-floor-aware planner env loaded"
