#!/usr/bin/env bash
# V41: beat-decoupled support stabilizer for slow-tempo Dunhuang bending.
# Use on top of V40 floor-aware leg IK.  It targets visual foot micro-sliding
# and beat-synchronous frame jitter while preserving slow phrase-level motion.
export EDGE_ROOT="${EDGE_ROOT:-/home/disk/lsm/storage/EDGE}"
export PYTHONPATH="$EDGE_ROOT${PYTHONPATH:+:$PYTHONPATH}"

# Keep the V40 floor-aware foundation.
export V40_FLOOR_AWARE_LEG_IK=${V40_FLOOR_AWARE_LEG_IK:-1}
export V40_FLOOR_IK_STEPS=${V40_FLOOR_IK_STEPS:-15}
export V40_FLOOR_IK_LR=${V40_FLOOR_IK_LR:-0.015}
export V40_FLOOR_IK_FLOOR_WEIGHT=${V40_FLOOR_IK_FLOOR_WEIGHT:-12.0}
export V40_FLOOR_IK_ROOT_WEIGHT=${V40_FLOOR_IK_ROOT_WEIGHT:-0.08}
export V40_FLOOR_IK_ROT_WEIGHT=${V40_FLOOR_IK_ROT_WEIGHT:-0.80}
export V40_FLOOR_IK_TEMPORAL_WEIGHT=${V40_FLOOR_IK_TEMPORAL_WEIGHT:-0.05}
export V40_FLOOR_IK_ANATOMY_WEIGHT=${V40_FLOOR_IK_ANATOMY_WEIGHT:-20.0}
export V40_FLOOR_IK_MAX_ROOT_DELTA=${V40_FLOOR_IK_MAX_ROOT_DELTA:-0.10}
export V40_FLOOR_IK_CONTEXT_FRAMES=${V40_FLOOR_IK_CONTEXT_FRAMES:-4}
export V40_FLOOR_IK_LOWER_JOINTS=${V40_FLOOR_IK_LOWER_JOINTS:-lhip,rhip,lknee,rknee,lankle,rankle,ltoes,rtoes}
export V40_ANATOMY_KNEE_GUARD=${V40_ANATOMY_KNEE_GUARD:-1}
export V40_KNEE_BAD_PITCH_SIGN=${V40_KNEE_BAD_PITCH_SIGN:-positive}

export V40_ANKLE_PITCH_CLAMP=${V40_ANKLE_PITCH_CLAMP:-1}
export V40_ANKLE_CLAMP_MAX_DEG=${V40_ANKLE_CLAMP_MAX_DEG:-22.0}
export V40_ANKLE_CLAMP_FOOT_LENGTH=${V40_ANKLE_CLAMP_FOOT_LENGTH:-0.16}
export V40_ANKLE_CLAMP_CONTACT_MAX=${V40_ANKLE_CLAMP_CONTACT_MAX:-0.25}
export V40_ANKLE_CLAMP_SMOOTH_WINDOW=${V40_ANKLE_CLAMP_SMOOTH_WINDOW:-5}

# Conservative contact inference and footplant gate.
export V39_CONTACT_HYSTERESIS=${V39_CONTACT_HYSTERESIS:-1}
export V39_CONTACT_ON_THRESHOLD=${V39_CONTACT_ON_THRESHOLD:-0.58}
export V39_CONTACT_OFF_THRESHOLD=${V39_CONTACT_OFF_THRESHOLD:-0.42}
export V39_REJECT_MOVING_FOOTPLANTS=${V39_REJECT_MOVING_FOOTPLANTS:-1}
export V39_MAX_FOOTPLANT_SEGMENT_ERROR=${V39_MAX_FOOTPLANT_SEGMENT_ERROR:-0.055}
export V39_MAX_FOOTPLANT_SEGMENT_P95=${V39_MAX_FOOTPLANT_SEGMENT_P95:-0.110}
export V39_MAX_FOOTPLANT_SEGMENT_FRAMES=${V39_MAX_FOOTPLANT_SEGMENT_FRAMES:-120}
export V38_CONTACT_DENOISE=${V38_CONTACT_DENOISE:-1}
export V38_CONTACT_MEDIAN_SIZE=${V38_CONTACT_MEDIAN_SIZE:-5}
export V38_CONTACT_CLOSE_HOLES=${V38_CONTACT_CLOSE_HOLES:-7}
export V38_CONTACT_OPEN_SPIKES=${V38_CONTACT_OPEN_SPIKES:-4}
export V38_CONTACT_LOCK_BLEND_FRAMES=${V38_CONTACT_LOCK_BLEND_FRAMES:-6}
export V34_CONTACT_LOCK_STRENGTH=${V34_CONTACT_LOCK_STRENGTH:-0.70}
export V34_CONTACT_LOCK_MAX_ROOT_CORRECTION=${V34_CONTACT_LOCK_MAX_ROOT_CORRECTION:-0.08}
export V39_ROOT_CORR_MAX_STEP=${V39_ROOT_CORR_MAX_STEP:-0.010}
export V39_ROOT_CORR_MAX_ACCEL=${V39_ROOT_CORR_MAX_ACCEL:-0.0035}
export V39_SUPPORT_ROOT_VELOCITY_DAMPING=${V39_SUPPORT_ROOT_VELOCITY_DAMPING:-0.08}

# Floor correction: keep accepted V40 behavior, do not over-lift pelvis.
export V34_FLOOR_QUANTILE=${V34_FLOOR_QUANTILE:-0.03}
export V34_FLOOR_MARGIN=${V34_FLOOR_MARGIN:-0.006}
export V34_FLOOR_STRENGTH=${V34_FLOOR_STRENGTH:-1.00}
export V34_FLOOR_MAX_LIFT=${V34_FLOOR_MAX_LIFT:-0.20}
export V34_FLOOR_SMOOTH_WINDOW=${V34_FLOOR_SMOOTH_WINDOW:-9}
export V34_FLOOR_SUPPORT_DAMPING=${V34_FLOOR_SUPPORT_DAMPING:-0.08}

# V41 beat-decoupled support stabilizer.
export V41_BEAT_DECOUPLED_SUPPORT_STABILIZER=${V41_BEAT_DECOUPLED_SUPPORT_STABILIZER:-1}
export V41_SUPPORT_SPEED_MAX=${V41_SUPPORT_SPEED_MAX:-0.022}
export V41_SUPPORT_MASK_SMOOTH=${V41_SUPPORT_MASK_SMOOTH:-9}
export V41_ROOT_XZ_CUTOFF_HZ=${V41_ROOT_XZ_CUTOFF_HZ:-1.65}
export V41_ROOT_XZ_FILTER_STRENGTH=${V41_ROOT_XZ_FILTER_STRENGTH:-0.82}
export V41_ROOT_XZ_MAX_STEP=${V41_ROOT_XZ_MAX_STEP:-0.010}
export V41_ROOT_XZ_MAX_ACCEL=${V41_ROOT_XZ_MAX_ACCEL:-0.0035}
export V41_FINAL_FOOTPLANT_RELOCK=${V41_FINAL_FOOTPLANT_RELOCK:-1}
export V41_RELOCK_MAX_SEGMENT_MEAN=${V41_RELOCK_MAX_SEGMENT_MEAN:-0.035}
export V41_RELOCK_MAX_SEGMENT_P95=${V41_RELOCK_MAX_SEGMENT_P95:-0.075}
export V41_RELOCK_MAX_SEGMENT_FRAMES=${V41_RELOCK_MAX_SEGMENT_FRAMES:-140}
export V41_RELOCK_STRENGTH=${V41_RELOCK_STRENGTH:-0.62}
export V41_RELOCK_CUTOFF_HZ=${V41_RELOCK_CUTOFF_HZ:-1.45}
export V41_RELOCK_MAX_CORRECTION=${V41_RELOCK_MAX_CORRECTION:-0.025}
export V41_RELOCK_MAX_STEP=${V41_RELOCK_MAX_STEP:-0.008}
export V41_RELOCK_MAX_ACCEL=${V41_RELOCK_MAX_ACCEL:-0.0025}
export V41_SUPPORT_LOWER_ROT_FILTER=${V41_SUPPORT_LOWER_ROT_FILTER:-1}
export V41_SUPPORT_LOWER_ROT_JOINTS=${V41_SUPPORT_LOWER_ROT_JOINTS:-lhip,rhip,lknee,rknee,lankle,rankle,ltoes,rtoes}
export V41_SUPPORT_LOWER_CUTOFF_HZ=${V41_SUPPORT_LOWER_CUTOFF_HZ:-2.25}
export V41_SUPPORT_LOWER_STRENGTH=${V41_SUPPORT_LOWER_STRENGTH:-0.38}

# Upper-body residual filter remains mild; V41 focuses on feet/root/lower body.
export V39_COLLISION_IK=${V39_COLLISION_IK:-0}
export V39_BUTTERWORTH_RESIDUAL_ONLY=${V39_BUTTERWORTH_RESIDUAL_ONLY:-1}
export V39_BUTTERWORTH_ROLLBACK_IF_WORSE=${V39_BUTTERWORTH_ROLLBACK_IF_WORSE:-1}
export V38_BUTTERWORTH_FILTER=${V38_BUTTERWORTH_FILTER:-1}
export V38_BUTTERWORTH_CUTOFF_HZ=${V38_BUTTERWORTH_CUTOFF_HZ:-3.4}
export V38_BUTTERWORTH_STRENGTH=${V38_BUTTERWORTH_STRENGTH:-0.38}
export V38_BUTTERWORTH_JOINTS=${V38_BUTTERWORTH_JOINTS:-lwrist,rwrist,lhand,rhand}
export V34_OUTPUT_SMOOTH=0

# Generation-side slow-bend recommendations; consumed by existing scheduler/env.
export V41_SLOW_BEND_MODE=${V41_SLOW_BEND_MODE:-1}
export V34_RHYTHM_WEIGHT=${V34_RHYTHM_WEIGHT:-0.75}
export V26_ACTIVITY_WEIGHT=${V26_ACTIVITY_WEIGHT:-0.18}
export V26_MIN_SUBPHRASE_SECONDS=${V26_MIN_SUBPHRASE_SECONDS:-2.10}
export V26_MAX_EVENTS_PER_PHRASE=${V26_MAX_EVENTS_PER_PHRASE:-3}
export V26_SLOT_BEAT_SNAP_SECONDS=${V26_SLOT_BEAT_SNAP_SECONDS:-0.12}
export V26_TRANSITION_MIN_FRAMES=${V26_TRANSITION_MIN_FRAMES:-22}
export V26_TRANSITION_MAX_FRAMES=${V26_TRANSITION_MAX_FRAMES:-60}

# Native-floor source cleaning / retrieval prior from V40.
export V40_NATIVE_FLOOR_PENALTY=${V40_NATIVE_FLOOR_PENALTY:-1}
export V40_NATIVE_FLOOR_TOLERANCE_M=${V40_NATIVE_FLOOR_TOLERANCE_M:-0.04}
export V40_NATIVE_FLOOR_PENALTY_WEIGHT=${V40_NATIVE_FLOOR_PENALTY_WEIGHT:-8.0}
export V40_NATIVE_FLOOR_QUANTILE=${V40_NATIVE_FLOOR_QUANTILE:-0.05}
export V40_NATIVE_FLOOR_MARGIN=${V40_NATIVE_FLOOR_MARGIN:-0.006}

export V41_DEVICE=${V41_DEVICE:-cuda}
echo "[V41] beat-decoupled support stabilizer env loaded"
