#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Continuous SO(3) transition INR and latent diffusion for EDGE V30.

The representation remains the native EDGE 151D motion format, but the learned
component is no longer tied to a fixed output frame count.  A shared implicit
neural representation (INR) decodes a latent transition code at arbitrary
normalised time coordinates.  The decoder predicts a bounded residual over an
endpoint-velocity-aware SO(3) Hermite base path, so endpoint pose, root position
and first-order boundary behaviour remain explicit rather than being delegated
to a black-box network.

The latent code is generated by a compact conditional diffusion model.  This is
substantially cheaper and more stable than diffusing a variable-length 151D
sequence, while preserving continuous-time decoding.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Dict, Tuple

import torch
import torch.nn.functional as F
from pytorch3d.transforms import (
    axis_angle_to_matrix,
    matrix_to_axis_angle,
    matrix_to_rotation_6d,
    rotation_6d_to_matrix,
)

from tools.v29_motion_geometry import (
    CONTACT,
    MOTION_DIM,
    NUM_JOINTS,
    ROOT,
    ROOT_X,
    ROOT_Y,
    ROOT_Z,
    ROT,
    motion_rotation_matrices_torch,
    project_motion_rotations_torch,
)


@dataclass
class V30INRConfig:
    motion_dim: int = MOTION_DIM
    music_dim: int = 12
    latent_dim: int = 128
    condition_dim: int = 256
    encoder_hidden: int = 320
    inr_hidden: int = 320
    inr_layers: int = 5
    fourier_bands: int = 10
    diffusion_hidden: int = 512
    diffusion_blocks: int = 6
    residual_rotation_scale: float = 0.40
    residual_root_y_scale: float = 0.10
    residual_contact_scale: float = 0.25
    max_len: int = 120
    dropout: float = 0.08


class SinusoidalEmbedding(torch.nn.Module):
    def __init__(self, dim: int) -> None:
        super().__init__()
        self.dim = int(dim)

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        x = value.reshape(-1, 1)
        half = max(1, self.dim // 2)
        frequencies = torch.exp(
            torch.linspace(
                math.log(1.0),
                math.log(10000.0),
                half,
                device=x.device,
                dtype=x.dtype,
            )
        )
        phase = x / frequencies.reshape(1, -1)
        embedding = torch.cat([torch.sin(phase), torch.cos(phase)], dim=-1)
        if embedding.shape[-1] < self.dim:
            embedding = F.pad(embedding, (0, self.dim - embedding.shape[-1]))
        return embedding[..., : self.dim]


def continuous_time_features(t: torch.Tensor, bands: int) -> torch.Tensor:
    """Fourier coordinate encoding for t in [0, 1]."""
    if t.shape[-1] != 1:
        t = t[..., :1]
    frequencies = (2.0 ** torch.arange(
        int(bands), device=t.device, dtype=t.dtype
    )).reshape(*([1] * (t.ndim - 1)), -1)
    phase = math.pi * t * frequencies
    return torch.cat(
        [t, t * t, torch.sin(phase), torch.cos(phase)], dim=-1
    )


def _safe_rotation_from_frame(frame: torch.Tensor) -> torch.Tensor:
    return rotation_6d_to_matrix(
        frame[..., ROT].reshape(*frame.shape[:-1], NUM_JOINTS, 6)
    )


def _limit_vector_norm(vector: torch.Tensor, maximum: torch.Tensor) -> torch.Tensor:
    norm = torch.linalg.vector_norm(vector, dim=-1, keepdim=True).clamp_min(1e-8)
    return vector * torch.minimum(torch.ones_like(norm), maximum / norm)


def so3_hermite_base(
    start: torch.Tensor,
    end: torch.Tensor,
    start_velocity: torch.Tensor,
    end_velocity: torch.Tensor,
    t: torch.Tensor,
    length_frames: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Return base contacts, root and local rotations at arbitrary coordinates.

    Args:
        start/end: [B,151] endpoint frames.
        start_velocity: first target frame minus start frame, [B,151].
        end_velocity: end frame minus last target frame, [B,151].
        t: [B,N,1] continuous coordinates in [0,1].
        length_frames: [B,1] number of in-between frames.
    """
    if t.shape[-1] != 1:
        t = t[..., :1]
    b, n, _ = t.shape
    dtype = start.dtype

    r0 = _safe_rotation_from_frame(start)
    r1 = _safe_rotation_from_frame(end)
    start_next = project_motion_rotations_torch(start + start_velocity)
    end_prev = project_motion_rotations_torch(end - end_velocity)
    r_start_next = _safe_rotation_from_frame(start_next)
    r_end_prev = _safe_rotation_from_frame(end_prev)

    relative = torch.matmul(r0.transpose(-1, -2), r1)
    delta = matrix_to_axis_angle(relative)
    omega0 = matrix_to_axis_angle(torch.matmul(r0.transpose(-1, -2), r_start_next))
    omega1 = matrix_to_axis_angle(torch.matmul(r_end_prev.transpose(-1, -2), r1))

    scale = (length_frames + 1.0).reshape(b, 1, 1).to(dtype)
    m0 = omega0 * scale
    m1 = omega1 * scale
    maximum = torch.linalg.vector_norm(delta, dim=-1, keepdim=True) + 0.45
    m0 = _limit_vector_norm(m0, maximum)
    m1 = _limit_vector_norm(m1, maximum)

    u = t.reshape(b, n, 1, 1)
    h10 = u**3 - 2.0 * u**2 + u
    h01 = -2.0 * u**3 + 3.0 * u**2
    h11 = u**3 - u**2
    tangent = (
        h10 * m0[:, None]
        + h01 * delta[:, None]
        + h11 * m1[:, None]
    )
    tangent_norm = torch.linalg.vector_norm(tangent, dim=-1, keepdim=True).clamp_min(1e-8)
    tangent_cap = torch.linalg.vector_norm(delta, dim=-1, keepdim=True)[:, None] + 0.60
    tangent = tangent * torch.minimum(
        torch.ones_like(tangent_norm), tangent_cap / tangent_norm
    )
    rotations = torch.matmul(r0[:, None], axis_angle_to_matrix(tangent))

    root0 = start[..., ROOT]
    root1 = end[..., ROOT]
    root_v0 = start_velocity[..., ROOT]
    root_v1 = end_velocity[..., ROOT]
    root_scale = (length_frames + 1.0).reshape(b, 1, 1).to(dtype)
    u_root = t
    h00 = 2.0 * u_root**3 - 3.0 * u_root**2 + 1.0
    h10_root = u_root**3 - 2.0 * u_root**2 + u_root
    h01_root = -2.0 * u_root**3 + 3.0 * u_root**2
    h11_root = u_root**3 - u_root**2
    root = (
        h00 * root0[:, None]
        + h10_root * root_scale * root_v0[:, None]
        + h01_root * root1[:, None]
        + h11_root * root_scale * root_v1[:, None]
    )

    smooth = t * t * (3.0 - 2.0 * t)
    contacts = (
        (1.0 - smooth) * start[:, None, CONTACT]
        + smooth * end[:, None, CONTACT]
    )
    return contacts, root, rotations


class ConditionEncoder(torch.nn.Module):
    def __init__(self, config: V30INRConfig) -> None:
        super().__init__()
        input_dim = 4 * config.motion_dim + config.music_dim + 1
        self.music_dim = int(config.music_dim)
        self.net = torch.nn.Sequential(
            torch.nn.LayerNorm(input_dim),
            torch.nn.Linear(input_dim, config.condition_dim * 2),
            torch.nn.SiLU(),
            torch.nn.Dropout(config.dropout),
            torch.nn.Linear(config.condition_dim * 2, config.condition_dim),
            torch.nn.SiLU(),
        )

    def forward(
        self,
        start: torch.Tensor,
        end: torch.Tensor,
        start_velocity: torch.Tensor,
        end_velocity: torch.Tensor,
        music: torch.Tensor,
        length_norm: torch.Tensor,
    ) -> torch.Tensor:
        if music.shape[-1] < self.music_dim:
            music = F.pad(music, (0, self.music_dim - music.shape[-1]))
        elif music.shape[-1] > self.music_dim:
            music = music[..., : self.music_dim]
        return self.net(torch.cat(
            [start, end, start_velocity, end_velocity, music, length_norm],
            dim=-1,
        ))


class MaskedTemporalBlock(torch.nn.Module):
    def __init__(self, channels: int, dilation: int, dropout: float) -> None:
        super().__init__()
        groups = 8 if channels % 8 == 0 else 1
        self.norm1 = torch.nn.GroupNorm(groups, channels)
        self.conv1 = torch.nn.Conv1d(
            channels, channels, 3, padding=dilation, dilation=dilation
        )
        self.norm2 = torch.nn.GroupNorm(groups, channels)
        self.conv2 = torch.nn.Conv1d(channels, channels, 3, padding=1)
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        h = self.dropout(self.conv1(F.silu(self.norm1(x))))
        h = self.conv2(F.silu(self.norm2(h)))
        return (x + h) * mask[:, None]


class TransitionINREncoder(torch.nn.Module):
    def __init__(self, config: V30INRConfig) -> None:
        super().__init__()
        self.input = torch.nn.Conv1d(config.motion_dim + 2, config.encoder_hidden, 1)
        self.blocks = torch.nn.ModuleList([
            MaskedTemporalBlock(config.encoder_hidden, dilation, config.dropout)
            for dilation in (1, 2, 4, 8, 16, 32, 1, 2)
        ])
        pooled_dim = config.encoder_hidden * 3 + config.condition_dim
        self.mu = torch.nn.Sequential(
            torch.nn.LayerNorm(pooled_dim),
            torch.nn.Linear(pooled_dim, config.encoder_hidden),
            torch.nn.SiLU(),
            torch.nn.Linear(config.encoder_hidden, config.latent_dim),
        )
        self.logvar = torch.nn.Sequential(
            torch.nn.LayerNorm(pooled_dim),
            torch.nn.Linear(pooled_dim, config.encoder_hidden),
            torch.nn.SiLU(),
            torch.nn.Linear(config.encoder_hidden, config.latent_dim),
        )
        torch.nn.init.constant_(self.logvar[-1].bias, -3.0)

    def forward(
        self,
        motion: torch.Tensor,
        mask: torch.Tensor,
        condition: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        b, k, _ = motion.shape
        coordinate = torch.linspace(
            1.0 / (k + 1), k / (k + 1), k,
            device=motion.device, dtype=motion.dtype,
        ).reshape(1, k, 1).expand(b, -1, -1)
        features = torch.cat([motion, coordinate, mask[..., None]], dim=-1)
        x = self.input(features.transpose(1, 2))
        for block in self.blocks:
            x = block(x, mask)
        sequence = x.transpose(1, 2)
        weight = mask[..., None]
        denominator = weight.sum(dim=1).clamp_min(1.0)
        mean = (sequence * weight).sum(dim=1) / denominator
        centered = sequence - mean[:, None]
        std = torch.sqrt(
            (centered.square() * weight).sum(dim=1) / denominator + 1e-6
        )
        maximum = sequence.masked_fill(mask[..., None] < 0.5, -1e4).amax(dim=1)
        pooled = torch.cat([mean, std, maximum, condition], dim=-1)
        return self.mu(pooled), self.logvar(pooled).clamp(-8.0, 4.0)


class SineLayer(torch.nn.Module):
    def __init__(self, in_dim: int, out_dim: int, omega: float = 24.0) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(in_dim, out_dim)
        self.omega = float(omega)
        bound = math.sqrt(6.0 / max(in_dim, 1)) / self.omega
        torch.nn.init.uniform_(self.linear.weight, -bound, bound)
        torch.nn.init.zeros_(self.linear.bias)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return torch.sin(self.omega * self.linear(x))


class ContinuousResidualINR(torch.nn.Module):
    def __init__(self, config: V30INRConfig) -> None:
        super().__init__()
        self.config = config
        time_dim = 2 + 2 * config.fourier_bands
        input_dim = time_dim + config.latent_dim + config.condition_dim
        layers = [SineLayer(input_dim, config.inr_hidden)]
        for _ in range(max(1, config.inr_layers - 2)):
            layers.append(SineLayer(config.inr_hidden, config.inr_hidden))
        self.layers = torch.nn.ModuleList(layers)
        self.output = torch.nn.Linear(
            config.inr_hidden,
            NUM_JOINTS * 3 + 1 + 4,
        )
        torch.nn.init.normal_(self.output.weight, mean=0.0, std=1e-4)
        torch.nn.init.zeros_(self.output.bias)

    def forward(
        self,
        t: torch.Tensor,
        latent: torch.Tensor,
        condition: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        b, n, _ = t.shape
        time_feature = continuous_time_features(t, self.config.fourier_bands)
        latent_feature = latent[:, None].expand(-1, n, -1)
        condition_feature = condition[:, None].expand(-1, n, -1)
        x = torch.cat([time_feature, latent_feature, condition_feature], dim=-1)
        for layer in self.layers:
            x = layer(x)
        output = self.output(x)
        rotation = output[..., : NUM_JOINTS * 3].reshape(b, n, NUM_JOINTS, 3)
        root_y = output[..., NUM_JOINTS * 3 : NUM_JOINTS * 3 + 1]
        contacts = output[..., NUM_JOINTS * 3 + 1 :]
        envelope = torch.sin(math.pi * t).square()
        rotation = torch.tanh(rotation) * envelope[..., None] * float(
            self.config.residual_rotation_scale
        )
        root_y = torch.tanh(root_y) * envelope * float(
            self.config.residual_root_y_scale
        )
        contacts = torch.tanh(contacts) * envelope * float(
            self.config.residual_contact_scale
        )
        return rotation, root_y, contacts


class LatentResidualBlock(torch.nn.Module):
    def __init__(self, hidden: int, cond_dim: int, dropout: float) -> None:
        super().__init__()
        self.norm = torch.nn.LayerNorm(hidden)
        self.linear1 = torch.nn.Linear(hidden, hidden * 2)
        self.linear2 = torch.nn.Linear(hidden * 2, hidden)
        self.cond = torch.nn.Linear(cond_dim, hidden * 2)
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, condition: torch.Tensor) -> torch.Tensor:
        gamma, beta = self.cond(condition).chunk(2, dim=-1)
        h = self.norm(x) * (1.0 + gamma) + beta
        h = self.linear2(self.dropout(F.silu(self.linear1(h))))
        return x + h


class LatentDiffusionDenoiser(torch.nn.Module):
    def __init__(self, config: V30INRConfig) -> None:
        super().__init__()
        self.time = torch.nn.Sequential(
            SinusoidalEmbedding(96),
            torch.nn.Linear(96, config.condition_dim),
            torch.nn.SiLU(),
            torch.nn.Linear(config.condition_dim, config.condition_dim),
        )
        self.input = torch.nn.Linear(config.latent_dim, config.diffusion_hidden)
        self.condition = torch.nn.Linear(
            config.condition_dim, config.condition_dim
        )
        self.blocks = torch.nn.ModuleList([
            LatentResidualBlock(
                config.diffusion_hidden,
                config.condition_dim,
                config.dropout,
            )
            for _ in range(config.diffusion_blocks)
        ])
        self.output = torch.nn.Sequential(
            torch.nn.LayerNorm(config.diffusion_hidden),
            torch.nn.SiLU(),
            torch.nn.Linear(config.diffusion_hidden, config.latent_dim),
        )
        torch.nn.init.normal_(self.output[-1].weight, mean=0.0, std=1e-3)
        torch.nn.init.zeros_(self.output[-1].bias)

    def forward(
        self,
        noisy_latent: torch.Tensor,
        diffusion_time: torch.Tensor,
        condition: torch.Tensor,
    ) -> torch.Tensor:
        cond = self.condition(condition) + self.time(diffusion_time)
        x = self.input(noisy_latent)
        for block in self.blocks:
            x = block(x, cond)
        return self.output(x)


class V30ContinuousTransitionSystem(torch.nn.Module):
    def __init__(self, config: V30INRConfig) -> None:
        super().__init__()
        self.config = config
        self.condition_encoder = ConditionEncoder(config)
        self.encoder = TransitionINREncoder(config)
        self.inr = ContinuousResidualINR(config)
        self.diffusion = LatentDiffusionDenoiser(config)

    def condition(
        self,
        start: torch.Tensor,
        end: torch.Tensor,
        start_velocity: torch.Tensor,
        end_velocity: torch.Tensor,
        music: torch.Tensor,
        length_frames: torch.Tensor,
    ) -> torch.Tensor:
        length_norm = (
            length_frames.reshape(-1, 1) / float(max(self.config.max_len, 1))
        ).clamp(0.0, 1.5)
        return self.condition_encoder(
            start,
            end,
            start_velocity,
            end_velocity,
            music,
            length_norm,
        )

    def encode(
        self,
        motion: torch.Tensor,
        mask: torch.Tensor,
        condition: torch.Tensor,
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.encoder(motion, mask, condition)

    @staticmethod
    def reparameterize(
        mean: torch.Tensor,
        logvar: torch.Tensor,
        deterministic: bool = False,
    ) -> torch.Tensor:
        if deterministic:
            return mean
        return mean + torch.randn_like(mean) * torch.exp(0.5 * logvar)

    def decode(
        self,
        latent: torch.Tensor,
        start: torch.Tensor,
        end: torch.Tensor,
        start_velocity: torch.Tensor,
        end_velocity: torch.Tensor,
        condition: torch.Tensor,
        t: torch.Tensor,
        length_frames: torch.Tensor,
    ) -> torch.Tensor:
        base_contact, base_root, base_rotation = so3_hermite_base(
            start,
            end,
            start_velocity,
            end_velocity,
            t,
            length_frames,
        )
        residual_rotation, residual_root_y, residual_contact = self.inr(
            t, latent, condition
        )
        rotation = torch.matmul(
            base_rotation,
            axis_angle_to_matrix(residual_rotation),
        )
        rot6d = matrix_to_rotation_6d(rotation).reshape(
            t.shape[0], t.shape[1], NUM_JOINTS * 6
        )
        contact = (base_contact + residual_contact).clamp(0.0, 1.0)
        root = base_root.clone()
        root[..., 1:2] = root[..., 1:2] + residual_root_y
        root[..., 0] = 0.0
        root[..., 2] = 0.0
        motion = torch.cat([contact, root, rot6d], dim=-1)
        return project_motion_rotations_torch(motion)


def linear_beta_schedule(
    steps: int,
    device: torch.device,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    beta = torch.linspace(1e-4, 0.02, int(steps), device=device)
    alpha = 1.0 - beta
    alpha_bar = torch.cumprod(alpha, dim=0)
    return beta, alpha, alpha_bar


def selected_timesteps(
    train_steps: int,
    inference_steps: int,
    device: torch.device,
) -> torch.Tensor:
    count = max(2, min(int(inference_steps), int(train_steps)))
    indices = torch.linspace(
        train_steps - 1, 0, count, device=device
    ).round().long()
    return torch.unique_consecutive(indices)


def config_from_dict(values: Dict[str, object]) -> V30INRConfig:
    fields = V30INRConfig.__dataclass_fields__
    clean = {key: values[key] for key in fields if key in values}
    return V30INRConfig(**clean)
