#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Band-limited continuous SO(3) transition model for EDGE V31.

V31 deliberately removes the high-frequency SIREN decoder used by V30.
A deterministic C2 quintic SO(3) path is always available.  The learned model
predicts only coefficients of a small analytic basis whose value, first
derivative and second derivative are zero at both endpoints:

    E(t) = 64 t^3 (1-t)^3
    residual(t) = E(t) * sum_k c_k P_k(2t-1)

This construction makes arbitrary-length decoding possible without giving the
network unrestricted high-frequency time functions. Contacts are never
generated by diffusion.  The learned residual affects local joint rotations
and root height only.
"""
from __future__ import annotations

import math
from dataclasses import asdict, dataclass
from typing import Dict, Tuple

import torch
import torch.nn.functional as F
from pytorch3d.transforms import (
    axis_angle_to_matrix,
    matrix_to_axis_angle,
    matrix_to_rotation_6d,
    rotation_6d_to_matrix,
)

from tools.v29_motion_geometry import (
    CONTACT,
    MOTION_DIM,
    NUM_JOINTS,
    ROOT,
    ROOT_X,
    ROOT_Y,
    ROOT_Z,
    ROT,
    project_motion_rotations_torch,
)

RESIDUAL_DIM = NUM_JOINTS * 3 + 1


@dataclass
class V31Config:
    motion_dim: int = MOTION_DIM
    music_dim: int = 12
    basis_count: int = 6
    coefficient_dim: int = RESIDUAL_DIM
    pca_dim: int = 96
    condition_dim: int = 256
    hidden_dim: int = 384
    diffusion_blocks: int = 6
    diffusion_steps: int = 100
    dropout: float = 0.08
    max_len: int = 120
    rotation_residual_cap: float = 0.16
    root_y_residual_cap: float = 0.045


def config_from_dict(values: Dict[str, object]) -> V31Config:
    allowed = set(V31Config.__dataclass_fields__)
    return V31Config(**{k: v for k, v in values.items() if k in allowed})


def config_to_dict(config: V31Config) -> Dict[str, object]:
    return asdict(config)


def _rotation(frame: torch.Tensor) -> torch.Tensor:
    return rotation_6d_to_matrix(
        frame[..., ROT].reshape(*frame.shape[:-1], NUM_JOINTS, 6)
    )


def _limit_norm(vector: torch.Tensor, maximum: torch.Tensor | float) -> torch.Tensor:
    norm = torch.linalg.vector_norm(vector, dim=-1, keepdim=True).clamp_min(1e-8)
    maximum_tensor = torch.as_tensor(
        maximum, dtype=vector.dtype, device=vector.device
    )
    return vector * torch.minimum(torch.ones_like(norm), maximum_tensor / norm)


def _safe_endpoint_rotation(
    frame: torch.Tensor,
    velocity: torch.Tensor,
    forward: bool,
) -> torch.Tensor:
    candidate = frame + velocity if forward else frame - velocity
    candidate = project_motion_rotations_torch(candidate)
    return _rotation(candidate)


def c2_quintic_so3_base(
    start: torch.Tensor,
    end: torch.Tensor,
    start_velocity: torch.Tensor,
    end_velocity: torch.Tensor,
    t: torch.Tensor,
    length_frames: torch.Tensor,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """C2 endpoint-safe base at arbitrary t in [0,1].

    The tangent polynomial satisfies endpoint pose and velocity, while its
    second derivative is zero at both endpoints. Endpoint velocity magnitudes
    are conservatively capped to avoid Hermite/quintic overshoot.
    """
    if t.shape[-1] != 1:
        t = t[..., :1]
    batch, count, _ = t.shape
    r0 = _rotation(start)
    r1 = _rotation(end)
    rs = _safe_endpoint_rotation(start, start_velocity, True)
    re = _safe_endpoint_rotation(end, end_velocity, False)

    delta = matrix_to_axis_angle(torch.matmul(r0.transpose(-1, -2), r1))
    omega0 = matrix_to_axis_angle(torch.matmul(r0.transpose(-1, -2), rs))
    omega1 = matrix_to_axis_angle(torch.matmul(re.transpose(-1, -2), r1))

    scale = (length_frames.reshape(batch, 1, 1) + 1.0).to(start.dtype)
    m0 = omega0 * scale
    m1 = omega1 * scale
    path_angle = torch.linalg.vector_norm(delta, dim=-1, keepdim=True)
    tangent_cap = torch.minimum(
        path_angle + 0.20,
        torch.full_like(path_angle, 0.75),
    )
    m0 = _limit_norm(m0, tangent_cap)
    m1 = _limit_norm(m1, tangent_cap)

    d = delta - m0
    e = m1 - m0
    a3 = 10.0 * d - 4.0 * e
    a4 = -15.0 * d + 7.0 * e
    a5 = 6.0 * d - 3.0 * e

    u = t.reshape(batch, count, 1, 1)
    tangent = (
        m0[:, None] * u
        + a3[:, None] * u**3
        + a4[:, None] * u**4
        + a5[:, None] * u**5
    )
    tangent = _limit_norm(
        tangent,
        torch.minimum(
            path_angle[:, None] + 0.20,
            torch.full_like(path_angle[:, None], 1.25),
        ),
    )
    rotations = torch.matmul(r0[:, None], axis_angle_to_matrix(tangent))

    root0 = start[..., ROOT]
    root1 = end[..., ROOT]
    root_scale = (length_frames.reshape(batch, 1) + 1.0).to(start.dtype)
    rv0 = start_velocity[..., ROOT] * root_scale
    rv1 = end_velocity[..., ROOT] * root_scale
    root_d = root1 - root0 - rv0
    root_e = rv1 - rv0
    root_a3 = 10.0 * root_d - 4.0 * root_e
    root_a4 = -15.0 * root_d + 7.0 * root_e
    root_a5 = 6.0 * root_d - 3.0 * root_e
    ur = t
    root = (
        root0[:, None]
        + rv0[:, None] * ur
        + root_a3[:, None] * ur**3
        + root_a4[:, None] * ur**4
        + root_a5[:, None] * ur**5
    )
    root[..., ROOT_X - ROOT.start] = 0.0
    root[..., ROOT_Z - ROOT.start] = 0.0

    smooth = t * t * t * (t * (t * 6.0 - 15.0) + 10.0)
    contacts = (
        (1.0 - smooth) * start[:, None, CONTACT]
        + smooth * end[:, None, CONTACT]
    )
    return contacts, root, rotations


def c2_basis(t: torch.Tensor, basis_count: int) -> torch.Tensor:
    """Low-order Legendre basis with C2-zero endpoint envelope."""
    if t.shape[-1] != 1:
        t = t[..., :1]
    x = 2.0 * t - 1.0
    polynomials = [torch.ones_like(x)]
    if basis_count > 1:
        polynomials.append(x)
    for order in range(2, int(basis_count)):
        next_value = (
            (2 * order - 1) * x * polynomials[-1]
            - (order - 1) * polynomials[-2]
        ) / float(order)
        polynomials.append(next_value)
    basis = torch.cat(polynomials[: int(basis_count)], dim=-1)
    envelope = 64.0 * t**3 * (1.0 - t) ** 3
    return envelope * basis


def decode_coefficients(
    coefficients: torch.Tensor,
    start: torch.Tensor,
    end: torch.Tensor,
    start_velocity: torch.Tensor,
    end_velocity: torch.Tensor,
    t: torch.Tensor,
    length_frames: torch.Tensor,
    config: V31Config,
) -> torch.Tensor:
    """Decode [B,basis,residual_dim] coefficients to native EDGE motion."""
    contacts, root, base_rotation = c2_quintic_so3_base(
        start, end, start_velocity, end_velocity, t, length_frames
    )
    basis = c2_basis(t, config.basis_count)
    residual = torch.einsum("bnk,bkd->bnd", basis, coefficients)
    rotation_residual = residual[..., : NUM_JOINTS * 3].reshape(
        residual.shape[0], residual.shape[1], NUM_JOINTS, 3
    )
    rotation_residual = _limit_norm(
        rotation_residual, float(config.rotation_residual_cap)
    )
    root_y_residual = residual[..., -1:].clamp(
        -float(config.root_y_residual_cap),
        float(config.root_y_residual_cap),
    )
    rotations = torch.matmul(
        base_rotation, axis_angle_to_matrix(rotation_residual)
    )
    rot6d = matrix_to_rotation_6d(rotations).reshape(
        residual.shape[0], residual.shape[1], NUM_JOINTS * 6
    )
    root = root.clone()
    root[..., 1:2] += root_y_residual
    root[..., 0] = 0.0
    root[..., 2] = 0.0
    motion = torch.cat([contacts.clamp(0.0, 1.0), root, rot6d], dim=-1)
    return project_motion_rotations_torch(motion)


def target_residual(
    target: torch.Tensor,
    start: torch.Tensor,
    end: torch.Tensor,
    start_velocity: torch.Tensor,
    end_velocity: torch.Tensor,
    t: torch.Tensor,
    length_frames: torch.Tensor,
) -> torch.Tensor:
    _, base_root, base_rotation = c2_quintic_so3_base(
        start, end, start_velocity, end_velocity, t, length_frames
    )
    target_rotation = _rotation(project_motion_rotations_torch(target))
    relative = torch.matmul(base_rotation.transpose(-1, -2), target_rotation)
    rotation = matrix_to_axis_angle(relative).reshape(
        target.shape[0], target.shape[1], NUM_JOINTS * 3
    )
    root_y = target[..., ROOT_Y : ROOT_Y + 1] - base_root[..., 1:2]
    return torch.cat([rotation, root_y], dim=-1)


def fit_coefficients(
    target: torch.Tensor,
    mask: torch.Tensor,
    start: torch.Tensor,
    end: torch.Tensor,
    start_velocity: torch.Tensor,
    end_velocity: torch.Tensor,
    length_frames: torch.Tensor,
    basis_count: int,
    ridge: float = 2e-3,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Weighted ridge fit. Returns coefficients and masked RMSE."""
    batch, maximum, _ = target.shape
    coordinates = torch.arange(
        maximum, device=target.device, dtype=target.dtype
    ).reshape(1, maximum, 1)
    denominator = length_frames.reshape(batch, 1, 1).clamp_min(1.0) + 1.0
    t = (coordinates + 1.0) / denominator
    t = t.clamp(0.0, 1.0)
    residual = target_residual(
        target, start, end, start_velocity, end_velocity, t, length_frames
    )
    basis = c2_basis(t, basis_count)
    weights = mask.to(target.dtype)
    coeffs = []
    reconstructions = []
    identity = torch.eye(
        basis_count, device=target.device, dtype=target.dtype
    )
    for index in range(batch):
        valid = weights[index] > 0.5
        bmat = basis[index, valid]
        values = residual[index, valid]
        if bmat.shape[0] < basis_count:
            coefficient = torch.zeros(
                (basis_count, RESIDUAL_DIM),
                device=target.device,
                dtype=target.dtype,
            )
        else:
            lhs = bmat.transpose(0, 1) @ bmat + float(ridge) * identity
            rhs = bmat.transpose(0, 1) @ values
            coefficient = torch.linalg.solve(lhs, rhs)
        coeffs.append(coefficient)
        reconstructions.append(basis[index] @ coefficient)
    coefficients = torch.stack(coeffs)
    reconstruction = torch.stack(reconstructions)
    error = torch.sqrt(
        (((reconstruction - residual) ** 2) * weights[..., None]).sum(
            dim=(1, 2)
        )
        / (
            weights.sum(dim=1).clamp_min(1.0)
            * float(RESIDUAL_DIM)
        )
    )
    return coefficients, error


def make_c2_transition_np(
    previous: "np.ndarray",
    following: "np.ndarray",
    length: int,
) -> "np.ndarray":
    """NumPy convenience baseline using endpoint context when available."""
    import numpy as np

    a = np.asarray(previous, dtype=np.float32)
    b = np.asarray(following, dtype=np.float32)
    k = max(0, int(length))
    if k == 0:
        return np.zeros((0, MOTION_DIM), dtype=np.float32)
    start_np = a[-1]
    end_np = b[0]
    start_velocity_np = (
        a[-1] - a[-2] if len(a) >= 2 else np.zeros_like(start_np)
    )
    end_velocity_np = (
        b[1] - b[0] if len(b) >= 2 else np.zeros_like(end_np)
    )
    with torch.no_grad():
        start = torch.from_numpy(start_np).reshape(1, -1)
        end = torch.from_numpy(end_np).reshape(1, -1)
        start_velocity = torch.from_numpy(start_velocity_np).reshape(1, -1)
        end_velocity = torch.from_numpy(end_velocity_np).reshape(1, -1)
        coordinates = torch.linspace(
            1.0 / (k + 1), k / (k + 1), k
        ).reshape(1, k, 1)
        length_frames = torch.tensor([[float(k)]])
        zero = torch.zeros(
            (1, 1, RESIDUAL_DIM), dtype=torch.float32
        )
        # Decode accepts any configured basis count; create a minimal config
        # and repeat the zero coefficient accordingly.
        config = V31Config(basis_count=1, pca_dim=1)
        motion = decode_coefficients(
            zero,
            start,
            end,
            start_velocity,
            end_velocity,
            coordinates,
            length_frames,
            config,
        )[0]
    return motion.cpu().numpy().astype(np.float32)


class SinusoidalEmbedding(torch.nn.Module):
    def __init__(self, dim: int) -> None:
        super().__init__()
        self.dim = int(dim)

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        x = value.reshape(-1, 1)
        half = max(1, self.dim // 2)
        frequency = torch.exp(
            torch.linspace(
                math.log(1.0), math.log(10000.0), half,
                device=x.device, dtype=x.dtype,
            )
        )
        phase = x / frequency.reshape(1, -1)
        embedding = torch.cat([torch.sin(phase), torch.cos(phase)], dim=-1)
        return F.pad(
            embedding,
            (0, max(0, self.dim - embedding.shape[-1])),
        )[..., : self.dim]


class ConditionEncoder(torch.nn.Module):
    def __init__(self, config: V31Config) -> None:
        super().__init__()
        self.music_dim = int(config.music_dim)
        input_dim = 4 * config.motion_dim + self.music_dim + 1
        self.net = torch.nn.Sequential(
            torch.nn.LayerNorm(input_dim),
            torch.nn.Linear(input_dim, config.hidden_dim),
            torch.nn.SiLU(),
            torch.nn.Dropout(config.dropout),
            torch.nn.Linear(config.hidden_dim, config.condition_dim),
            torch.nn.SiLU(),
        )

    def forward(
        self,
        start: torch.Tensor,
        end: torch.Tensor,
        start_velocity: torch.Tensor,
        end_velocity: torch.Tensor,
        music: torch.Tensor,
        length_frames: torch.Tensor,
        max_len: int,
    ) -> torch.Tensor:
        if music.shape[-1] < self.music_dim:
            music = F.pad(music, (0, self.music_dim - music.shape[-1]))
        elif music.shape[-1] > self.music_dim:
            music = music[..., : self.music_dim]
        length = (
            length_frames.reshape(-1, 1) / float(max(max_len, 1))
        ).clamp(0.0, 1.5)
        return self.net(torch.cat([
            start, end, start_velocity, end_velocity, music, length
        ], dim=-1))


class ResidualBlock(torch.nn.Module):
    def __init__(self, hidden: int, condition_dim: int, dropout: float) -> None:
        super().__init__()
        self.norm = torch.nn.LayerNorm(hidden)
        self.linear1 = torch.nn.Linear(hidden, hidden * 2)
        self.linear2 = torch.nn.Linear(hidden * 2, hidden)
        self.condition = torch.nn.Linear(condition_dim, hidden * 2)
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, x: torch.Tensor, condition: torch.Tensor) -> torch.Tensor:
        gamma, beta = self.condition(condition).chunk(2, dim=-1)
        h = self.norm(x) * (1.0 + gamma) + beta
        h = self.linear2(self.dropout(F.silu(self.linear1(h))))
        return x + h


class CoefficientDiffusion(torch.nn.Module):
    def __init__(self, config: V31Config) -> None:
        super().__init__()
        self.time = torch.nn.Sequential(
            SinusoidalEmbedding(96),
            torch.nn.Linear(96, config.condition_dim),
            torch.nn.SiLU(),
            torch.nn.Linear(config.condition_dim, config.condition_dim),
        )
        self.input = torch.nn.Linear(config.pca_dim, config.hidden_dim)
        self.blocks = torch.nn.ModuleList([
            ResidualBlock(
                config.hidden_dim, config.condition_dim, config.dropout
            )
            for _ in range(config.diffusion_blocks)
        ])
        self.output = torch.nn.Sequential(
            torch.nn.LayerNorm(config.hidden_dim),
            torch.nn.SiLU(),
            torch.nn.Linear(config.hidden_dim, config.pca_dim),
        )
        torch.nn.init.normal_(self.output[-1].weight, 0.0, 1e-3)
        torch.nn.init.zeros_(self.output[-1].bias)

    def forward(
        self,
        noisy: torch.Tensor,
        diffusion_time: torch.Tensor,
        condition: torch.Tensor,
    ) -> torch.Tensor:
        cond = condition + self.time(diffusion_time)
        x = self.input(noisy)
        for block in self.blocks:
            x = block(x, cond)
        return self.output(x)


class V31TransitionModel(torch.nn.Module):
    def __init__(self, config: V31Config) -> None:
        super().__init__()
        self.config = config
        self.condition_encoder = ConditionEncoder(config)
        self.diffusion = CoefficientDiffusion(config)

    def condition(
        self,
        start: torch.Tensor,
        end: torch.Tensor,
        start_velocity: torch.Tensor,
        end_velocity: torch.Tensor,
        music: torch.Tensor,
        length_frames: torch.Tensor,
    ) -> torch.Tensor:
        return self.condition_encoder(
            start, end, start_velocity, end_velocity,
            music, length_frames, self.config.max_len,
        )


def linear_beta_schedule(
    steps: int, device: torch.device
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    beta = torch.linspace(1e-4, 0.02, int(steps), device=device)
    alpha = 1.0 - beta
    alpha_bar = torch.cumprod(alpha, dim=0)
    return beta, alpha, alpha_bar


def selected_timesteps(
    train_steps: int, inference_steps: int, device: torch.device
) -> torch.Tensor:
    count = max(2, min(int(train_steps), int(inference_steps)))
    indices = torch.linspace(
        train_steps - 1, 0, count, device=device
    ).round().long()
    return torch.unique_consecutive(indices)
