#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Masked boundary inpainting for V34 whole-song composition.

The retrieval stage should reject clearly incompatible event pairs.  This file
handles the narrower research case that remains: a selected pair is globally
compatible, but the local stitch still carries visible endpoint jerk, contact
slip, or a small pose impulse.  Instead of smoothing only the generated
transition, we mask and redraw a short band around the boundary:

    kept A | [A tail, transition, B head] | kept B

The masked band is regenerated by the existing contact-aware latent diffusion
checkpoint and then split back into A tail, transition, and B head.  The total
music length is unchanged.
"""
from __future__ import annotations

import os
from typing import Any, Dict, Mapping, Tuple

import numpy as np
import torch

from tools.v27_transition_diffusion import sample_transition_diffusion
from tools.v29_motion_geometry import MOTION_DIM, ROOT_X, ROOT_Z, project_motion_rotations_np
from tools.v32_transition_quality import transition_risk


def _enabled(name: str, default: str = "0") -> bool:
    return os.getenv(name, default).strip().lower() in {"1", "true", "yes", "on"}


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.getenv(name, str(default)))
    except Exception:
        return float(default)


def _env_int(name: str, default: int) -> int:
    try:
        return int(float(os.getenv(name, str(default))))
    except Exception:
        return int(default)


def _absolute_checks(risk: Mapping[str, float]) -> Dict[str, bool]:
    return {
        "boundary_jerk": float(risk["boundary_joint_jerk_max"])
        <= _env_float("V34_MAX_BOUNDARY_JERK", 5000.0),
        "boundary_angular_jerk": float(risk["boundary_angular_jerk_max"])
        <= _env_float("V34_MAX_BOUNDARY_ANGULAR_JERK", 5000.0),
        "exit_rotation": float(risk["exit_rotation_step_rad"])
        <= _env_float("V34_MAX_EXIT_ROTATION_STEP_RAD", 0.12),
        "exit_fk": float(risk["exit_fk_jump"])
        <= _env_float("V34_MAX_EXIT_FK_JUMP", 0.040),
        "exit_acceleration": float(risk["exit_acceleration"])
        <= _env_float("V34_MAX_EXIT_ACCELERATION", 12.0),
    }


def _risk_score(risk: Mapping[str, float]) -> float:
    thresholds = {
        "boundary_joint_jerk_max": _env_float("V34_MAX_BOUNDARY_JERK", 5000.0),
        "boundary_angular_jerk_max": _env_float("V34_MAX_BOUNDARY_ANGULAR_JERK", 5000.0),
        "exit_rotation_step_rad": _env_float("V34_MAX_EXIT_ROTATION_STEP_RAD", 0.12),
        "exit_fk_jump": _env_float("V34_MAX_EXIT_FK_JUMP", 0.040),
        "exit_acceleration": _env_float("V34_MAX_EXIT_ACCELERATION", 12.0),
    }
    return float(max(
        float(risk[key]) / max(limit, 1e-8)
        for key, limit in thresholds.items()
    ))


def _boundary_compatibility_meta(part: Mapping[str, Any] | None) -> Dict[str, Any]:
    part_dict = dict(part or {})
    transition_meta = dict(part_dict.get("transition_meta", {}) or {})
    meta = transition_meta.get("boundary_compatibility", None)
    if meta is None:
        meta = part_dict.get("boundary_compat_meta", {})
    return dict(meta or {})


def _ratio_from_meta(
    meta: Mapping[str, Any],
    metric_key: str,
    limit_key: str | None = None,
) -> float:
    metrics = dict(meta.get("metrics", {}) or {})
    limits = dict(meta.get("limits", {}) or {})
    limit_key = limit_key or metric_key
    try:
        value = float(metrics.get(metric_key, 0.0))
        limit = float(limits.get(limit_key, 0.0))
    except Exception:
        return 0.0
    if limit <= 1e-8:
        return 0.0
    return float(value / limit)


def _visual_trigger_terms(meta: Mapping[str, Any]) -> Dict[str, Any]:
    pose_ratio = _ratio_from_meta(meta, "pose_jump")
    yaw_ratio = _ratio_from_meta(meta, "yaw_gap_deg")
    transition_ratio = _ratio_from_meta(meta, "transition_cost")
    contact_ratio = max(
        _ratio_from_meta(meta, "contact_jump"),
        _ratio_from_meta(meta, "contact_binary_jump"),
        _ratio_from_meta(meta, "support_count_jump"),
    )
    thresholds = {
        "pose_ratio": _env_float("V34_INPAINT_VISUAL_POSE_RATIO", 0.80),
        "yaw_ratio": _env_float("V34_INPAINT_VISUAL_YAW_RATIO", 0.80),
        "transition_ratio": _env_float("V34_INPAINT_VISUAL_TRANSITION_RATIO", 0.80),
        "contact_ratio": _env_float("V34_INPAINT_VISUAL_CONTACT_RATIO", 0.80),
    }
    ratios = {
        "pose_ratio": float(pose_ratio),
        "yaw_ratio": float(yaw_ratio),
        "transition_ratio": float(transition_ratio),
        "contact_ratio": float(contact_ratio),
    }
    fired = {
        key: bool(ratios[key] >= thresholds[key])
        for key in ratios
    }
    return {
        "enabled": _enabled("V34_INPAINT_VISUAL_HEURISTIC", "1"),
        "ratios": ratios,
        "thresholds": thresholds,
        "fired": fired,
        "active": bool(
            _enabled("V34_INPAINT_VISUAL_HEURISTIC", "1")
            and any(fired.values())
        ),
    }


def _should_inpaint(
    *,
    risk: Mapping[str, float],
    part: Mapping[str, Any] | None,
    diffusion_meta: Mapping[str, Any] | None,
) -> Tuple[bool, Dict[str, Any]]:
    score = _risk_score(risk)
    trigger = _env_float("V34_INPAINT_TRIGGER_RATIO", 0.72)
    compat_trigger = _env_float("V34_INPAINT_COMPAT_SCORE_TRIGGER", 0.45)
    compat_score = float((part or {}).get("boundary_compat_score", 0.0))
    transition_meta = dict((part or {}).get("transition_meta", {}) or {})
    relaxation_meta = dict(transition_meta.get("constraint_relaxation", {}) or {})
    visual_terms = _visual_trigger_terms(_boundary_compatibility_meta(part))
    relaxed_constraint = bool(
        _enabled("V34_INPAINT_ON_RELAXED_CONSTRAINT", "1")
        and (
            bool((part or {}).get("constraint_relaxed", False))
            or bool((part or {}).get("semantic_relaxed", False))
            or bool((part or {}).get("compat_relaxed", False))
            or bool((part or {}).get("contact_relaxed", False))
            or bool(relaxation_meta.get("active", False))
            or bool(relaxation_meta.get("used_due_to_empty_strict", False))
        )
    )
    fallback = bool((diffusion_meta or {}).get("fallback_to_c2_baseline", False))
    unsafe = not all(_absolute_checks(risk).values())
    reasons = {
        "risk_score": score,
        "risk_trigger": bool(score >= trigger),
        "compat_score": compat_score,
        "compat_trigger": bool(compat_score >= compat_trigger),
        "visual_heuristic": bool(visual_terms.get("active", False)),
        "visual_heuristic_terms": visual_terms,
        "relaxed_constraint": bool(relaxed_constraint),
        "relaxation_reasons": list(relaxation_meta.get("reasons", [])),
        "diffusion_fallback": fallback,
        "absolute_unsafe": bool(unsafe),
    }
    return bool(
        reasons["risk_trigger"]
        or reasons["compat_trigger"]
        or reasons["visual_heuristic"]
        or reasons["relaxed_constraint"]
        or reasons["diffusion_fallback"]
        or reasons["absolute_unsafe"]
    ), reasons


def _contexts(
    previous: np.ndarray,
    following: np.ndarray,
    tail: int,
    head: int,
    context: int,
) -> Tuple[np.ndarray, np.ndarray]:
    left_end = len(previous) - int(tail)
    left_start = max(0, left_end - int(context))
    right_start = int(head)
    right_end = min(len(following), right_start + int(context))
    return (
        previous[left_start:left_end].astype(np.float32),
        following[right_start:right_end].astype(np.float32),
    )


def maybe_inpaint_boundary(
    *,
    transition_bundle: Dict[str, Any] | None,
    previous_content: np.ndarray,
    transition: np.ndarray,
    content: np.ndarray,
    music_query: np.ndarray,
    device: torch.device | str,
    fps: float,
    blend: float,
    steps: int,
    part: Mapping[str, Any] | None = None,
    diffusion_meta: Mapping[str, Any] | None = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, Dict[str, Any]]:
    """Optionally redraw a masked boundary band.

    Returns ``(previous_content, transition, content, metadata)``.  Shapes and
    lengths are preserved even when inpainting is applied.
    """
    previous = np.asarray(previous_content, np.float32)
    trans = np.asarray(transition, np.float32)
    following = np.asarray(content, np.float32)
    meta: Dict[str, Any] = {
        "enabled": _enabled("V34_BOUNDARY_INPAINT", "0"),
        "applied": False,
    }
    if not meta["enabled"]:
        meta["reason"] = "disabled"
        return previous.copy(), trans.copy(), following.copy(), meta
    if len(trans) == 0:
        meta["reason"] = "zero_transition_length"
        return previous.copy(), trans.copy(), following.copy(), meta
    if transition_bundle is None and _enabled("V34_INPAINT_REQUIRE_DIFFUSION", "1"):
        meta["reason"] = "missing_transition_diffusion_bundle"
        return previous.copy(), trans.copy(), following.copy(), meta
    if previous.ndim != 2 or following.ndim != 2 or previous.shape[1] != MOTION_DIM or following.shape[1] != MOTION_DIM:
        meta["reason"] = "invalid_motion_shape"
        return previous.copy(), trans.copy(), following.copy(), meta

    risk_before = transition_risk(previous, trans, following, fps=float(fps))
    should, trigger_meta = _should_inpaint(
        risk=risk_before,
        part=part,
        diffusion_meta=diffusion_meta,
    )
    meta.update({
        "trigger": trigger_meta,
        "risk_before": risk_before,
        "risk_score_before": _risk_score(risk_before),
    })
    if not should and not _enabled("V34_INPAINT_ALWAYS", "0"):
        meta["reason"] = "below_trigger"
        return previous.copy(), trans.copy(), following.copy(), meta

    min_keep = max(2, _env_int("V34_INPAINT_MIN_KEEP_FRAMES", 4))
    tail = min(
        max(0, _env_int("V34_INPAINT_TAIL_FRAMES", 6)),
        max(0, len(previous) - min_keep),
    )
    head = min(
        max(0, _env_int("V34_INPAINT_HEAD_FRAMES", 6)),
        max(0, len(following) - min_keep),
    )
    if tail < 1 or head < 1:
        meta["reason"] = "insufficient_tail_or_head"
        meta["tail_frames"] = int(tail)
        meta["head_frames"] = int(head)
        return previous.copy(), trans.copy(), following.copy(), meta

    window_length = int(tail + len(trans) + head)
    if window_length <= 0:
        meta["reason"] = "empty_mask_window"
        return previous.copy(), trans.copy(), following.copy(), meta

    context = max(2, _env_int("V34_INPAINT_CONTEXT_FRAMES", 4))
    left_context, right_context = _contexts(previous, following, tail, head, context)
    if len(left_context) < 1 or len(right_context) < 1:
        meta["reason"] = "missing_anchor_context"
        return previous.copy(), trans.copy(), following.copy(), meta

    original_window = np.concatenate([
        previous[-tail:],
        trans.reshape(0, MOTION_DIM) if len(trans) == 0 else trans,
        following[:head],
    ], axis=0).astype(np.float32)

    redraw_blend = _env_float("V34_INPAINT_BLEND", float(blend))
    redraw_steps = _env_int("V34_INPAINT_STEPS", int(steps))
    redrawn, redraw_meta = sample_transition_diffusion(
        transition_bundle,
        left_context[-1],
        right_context[0],
        window_length,
        np.asarray(music_query, np.float32),
        rough=original_window,
        device=device,
        blend=redraw_blend,
        steps=redraw_steps,
        previous_context=left_context,
        next_context=right_context,
    )
    redrawn = np.asarray(redrawn, np.float32)
    if redrawn.shape != (window_length, MOTION_DIM) or not np.isfinite(redrawn).all():
        meta["reason"] = "invalid_redraw"
        meta["redraw_meta"] = redraw_meta
        return previous.copy(), trans.copy(), following.copy(), meta

    new_previous = previous.copy()
    new_transition = redrawn[tail:tail + len(trans)].copy()
    new_following = following.copy()
    new_previous[-tail:] = redrawn[:tail]
    new_following[:head] = redrawn[tail + len(trans):]
    for arr in (new_previous, new_transition, new_following):
        if len(arr):
            arr[:, ROOT_X] = 0.0
            arr[:, ROOT_Z] = 0.0
    new_previous = project_motion_rotations_np(new_previous)
    new_transition = project_motion_rotations_np(new_transition) if len(new_transition) else new_transition
    new_following = project_motion_rotations_np(new_following)

    risk_after = transition_risk(new_previous, new_transition, new_following, fps=float(fps))
    before_score = _risk_score(risk_before)
    after_score = _risk_score(risk_after)
    before_checks = _absolute_checks(risk_before)
    after_checks = _absolute_checks(risk_after)
    check_improvement = int(sum(after_checks.values()) - sum(before_checks.values()))
    absolute_improved = bool(
        check_improvement > 0
        or (
            float(risk_after["exit_acceleration"])
            < float(risk_before["exit_acceleration"])
            and float(risk_after["boundary_joint_jerk_max"])
            <= float(risk_before["boundary_joint_jerk_max"])
            * _env_float("V34_INPAINT_IMPROVE_JERK_TOL", 1.05)
        )
    )
    max_ratio = _env_float("V34_INPAINT_MAX_RISK_RATIO", 1.03)
    accept = bool(
        after_score <= before_score * max_ratio
        or (all(after_checks.values()) and not all(before_checks.values()))
        or (
            _enabled("V34_INPAINT_ACCEPT_IF_ABSOLUTE_IMPROVES", "1")
            and absolute_improved
        )
        or _enabled("V34_INPAINT_FORCE_ACCEPT", "0")
    )

    meta.update({
        "tail_frames": int(tail),
        "head_frames": int(head),
        "mask_window_frames": int(window_length),
        "context_frames": int(context),
        "redraw_meta": redraw_meta,
        "risk_after": risk_after,
        "absolute_checks_before": before_checks,
        "absolute_checks_after": after_checks,
        "absolute_check_improvement": int(check_improvement),
        "absolute_improved": bool(absolute_improved),
        "risk_score_after": float(after_score),
        "risk_ratio_after_over_before": float(after_score / max(before_score, 1e-8)),
        "accepted": bool(accept),
    })
    if not accept:
        meta["reason"] = "risk_gate_rejected"
        return previous.copy(), trans.copy(), following.copy(), meta

    meta["applied"] = True
    meta["reason"] = "accepted"
    return (
        new_previous.astype(np.float32),
        new_transition.astype(np.float32),
        new_following.astype(np.float32),
        meta,
    )
